apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "java-pipeline.labels" . | nindent 4 }}
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" $ }}-{{ include "java-pipeline.pipelinePrefix" . }}-mail-failure
data:
  ppl_logging_module.py: |-
{{ .Files.Get "scripts/util/ppl_logging_module.py" | indent 4 }}
  ppl_notification_link.py: |-
{{ .Files.Get "scripts/notification/ppl_notification_link.py" | indent 4 }}
  ppl_notification.py: |-
{{ .Files.Get "scripts/notification/ppl_notification.py" | indent 4 }}
  ppl_mail_failure.py: |-
{{ .Files.Get "scripts/notification/ppl_mail_failure.py" | indent 4 }}
