apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "java-pipeline.labels" . | nindent 4 }}
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" $ }}-{{ include "java-pipeline.pipelinePrefix" . }}-run-deployment
data:
  ppl_common_module.py: |-
{{ .Files.Get "scripts/util/ppl_common_module.py" | indent 4 }}
  ppl_http_module.py: |-
{{ .Files.Get "scripts/util/ppl_http_module.py" | indent 4 }}
  ppl_json_module.py: |-
{{ .Files.Get "scripts/util/ppl_json_module.py" | indent 4 }}
  ppl_logging_module.py: |-
{{ .Files.Get "scripts/util/ppl_logging_module.py" | indent 4 }}
