################################################################################################
# version of MEB
################################################################################################
meb.version=${meb.version.major}.${meb.version.minor}

################################################################################################
# version of SBG
################################################################################################
sbg.version=${sbg.version.major}.${sbg.version.minor}

################################################################################################
# version of SDL
################################################################################################
sdl.version=${sdl.version.major}.${sdl.version.minor}

################################################################################################
# version of SSP
################################################################################################
ssp.version=${ssp.version.major}.${ssp.version.minor}

################################################################################################
# version of SBA
################################################################################################
sba.version=${sba.version.major}.${sba.version.minor}

################################################################################################
# directories
################################################################################################
project.root.dir=.
#delivery.root.dir=${project.root.dir}/../../RELEASES
delivery.root.dir=${project.root.dir}/RELEASES

################################################################################################
# directories (PROJECTS)
################################################################################################
meb.commons.root.dir=${project.root.dir}/meb-commons
server.commons.root.dir=${project.root.dir}/server-commons
web.commons.root.dir=${project.root.dir}/web-commons
dhtmlx.xbeans.root.dir=${project.root.dir}/dhtmlx-xml-beans

meb.db.root.dir=${project.root.dir}/mebdb
meb.server.root.dir=${project.root.dir}/mebserver
meb.serverEAR.root.dir=${project.root.dir}/mebserverEAR
meb.web.root.dir=${project.root.dir}/mebweb
meb.webEAR.root.dir=${project.root.dir}/mebwebEAR
meb.wsclient.root.dir=${project.root.dir}/mebwsclient
meb.sdmx.xbeans.root.dir=${project.root.dir}/sdmx-xml-beans
meb.documentation.root.dir=${project.root.dir}/documentation

sbg.server.root.dir=${project.root.dir}/sbgserver
sbg.serverEAR.root.dir=${project.root.dir}/sbgserverEAR
sbg.web.root.dir=${project.root.dir}/sbgweb
sbg.webEAR.root.dir=${project.root.dir}/sbgwebEAR
sbg.wsclient.root.dir=${project.root.dir}/sbgwsclient
sbg.xbeans.root.dir=${project.root.dir}/sbg-xml-beans

sdl.server.root.dir=${project.root.dir}/sdlserver
sdl.serverEAR.root.dir=${project.root.dir}/sdlserverEAR
sdl.web.root.dir=${project.root.dir}/sdlweb
sdl.webEAR.root.dir=${project.root.dir}/sdlwebEAR
sdl.wsclient.root.dir=${project.root.dir}/sdlwsclient
sdl.xbeans.root.dir=${project.root.dir}/sdl-xml-beans

ssp.server.root.dir=${project.root.dir}/sspserver
ssp.serverEAR.root.dir=${project.root.dir}/sspserverEAR
ssp.web.root.dir=${project.root.dir}/sspweb
ssp.webEAR.root.dir=${project.root.dir}/sspwebEAR
ssp.wsclient.root.dir=${project.root.dir}/sspwsclient

sba.server.root.dir=${project.root.dir}/sbaserver
sba.serverEAR.root.dir=${project.root.dir}/sbaserverEAR
sba.web.root.dir=${project.root.dir}/sbaweb
sba.webEAR.root.dir=${project.root.dir}/sbawebEAR
sba.wsclient.root.dir=${project.root.dir}/sbawsclient

################################################################################################
# directories (COMMON)
################################################################################################
delivery.application.dir=${delivery.root.dir}/APPLICATIONS
delivery.application.package.dir=${delivery.root.dir}/PACKAGES
delivery.application.wsdl.version.parent.dir=${delivery.root.dir}/WSDL/${meb.version}
delivery.application.wsdl.version.dir=${delivery.application.wsdl.version.parent.dir}/wsdl_${meb.version}
delivery.application.ear.version.dir=${delivery.root.dir}/EAR/ear_${meb.version}

################################################################################################
# directories for database
################################################################################################
database.delivery.root.dir=${delivery.root.dir}/DATABASE
database.scripts.delivery.root.dir=${database.delivery.root.dir}/scripts
mebdb.database.dir=${meb.db.root.dir}/database
mebdb.flyway.scripts.dir=${mebdb.database.dir}/scripts
mebdb.flyway.delivery.scripts.dir=${database.delivery.version.dir}/sql
mebdb.flyway.delivery.conf.dir=${database.delivery.version.dir}/conf
mebdb.flyway.conf.dir=${meb.db.root.dir}/conf
database.delivery.version.dir=${database.delivery.root.dir}/database_${meb.version}

################################################################################################
# directories for MEB
################################################################################################
meb.delivery.root.dir=${delivery.root.dir}/MEB
meb.delivery.version.dir=${meb.delivery.root.dir}/V${meb.version}

meb.serverEAR.target.dir=${meb.serverEAR.root.dir}/target
meb.webEAR.target.dir=${meb.webEAR.root.dir}/target
meb.wsdl.root.dir=${meb.wsclient.root.dir}/src/wsdl

################################################################################################
# directories for SBG
################################################################################################
sbg.delivery.root.dir=${delivery.root.dir}/SBG
sbg.delivery.version.dir=${sbg.delivery.root.dir}/V${sbg.version}

sbg.serverEAR.target.dir=${sbg.serverEAR.root.dir}/target
sbg.webEAR.target.dir=${sbg.webEAR.root.dir}/target
sbg.wsdl.target.root.dir=${sbg.wsclient.root.dir}/target/classes/wsdl

################################################################################################
# directories for SDL
################################################################################################
sdl.delivery.root.dir=${delivery.root.dir}/SDL
sdl.delivery.version.dir=${sdl.delivery.root.dir}/V${sdl.version}

sdl.serverEAR.target.dir=${sdl.serverEAR.root.dir}/target
sdl.webEAR.target.dir=${sdl.webEAR.root.dir}/target
sdl.wsdl.root.dir=${sdl.wsclient.root.dir}/src/wsdl
sdl.wsdl.target.root.dir=${sdl.wsclient.root.dir}/target/classes/wsdl

################################################################################################
# directories for SSP
################################################################################################
ssp.delivery.root.dir=${delivery.root.dir}/SSP
ssp.delivery.version.dir=${ssp.delivery.root.dir}/V${ssp.version}

ssp.serverEAR.target.dir=${ssp.serverEAR.root.dir}/target
ssp.webEAR.target.dir=${ssp.webEAR.root.dir}/target
ssp.wsdl.root.dir=${ssp.wsclient.root.dir}/src/wsdl
ssp.wsdl.target.root.dir=${ssp.wsclient.root.dir}/target/classes/wsdl

################################################################################################
# directories for SBA
################################################################################################
sba.delivery.root.dir=${delivery.root.dir}/SBA
sba.delivery.version.dir=${sba.delivery.root.dir}/V${sba.version}

sba.serverEAR.target.dir=${sba.serverEAR.root.dir}/target
sba.webEAR.target.dir=${sba.webEAR.root.dir}/target
sba.wsdl.root.dir=${sba.wsclient.root.dir}/src/wsdl
sba.wsdl.target.root.dir=${sba.wsclient.root.dir}/target/classes/wsdl
