# --------------------------------
# Konfiguration properties
# --------------------------------
configuration.idmdomain=MEB
configuration.idmserverurl=https://services.gate-r.eiam.admin.ch/nevisidm/services/v1_45/AdminService
configuration.keyStore=
configuration.keyStorePassword=
configuration.sbgserverurl=http://localhost:7001/sbgserver
configuration.commonserverurl=http://localhost:7001/mebserver
configuration.idm.implementation=idmUserServiceMock