/****************************************************************************
 *	Stop in case of failure
 ****************************************************************************/
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

/****************************************************************************
 *	Grants for BFS_ADMIN_ROLE
 ****************************************************************************/
GRANT SELECT, UPDATE, INSERT, DELETE ON CODEGROUPS TO BFS_ADMIN_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCHOOLS TO BFS_ADMIN_ROLE; 

GRANT SELECT ON SDL_CONFIGDELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_SCHOOLS_CONFIGDELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_CANTONS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_DELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_INTERVENTIONS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_SCHOOLS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_CLASSES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_LEARNERS TO BFS_ADMIN_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_PLAUSIERRORS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_FILTERS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_PLAUSIS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_EXPORTS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDL_PARAMETERS TO BFS_ADMIN_ROLE; 

GRANT SELECT ON SSP_CONFIGDELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_SCHOOLS_CONFIGDELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_CANTONS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_DELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_INTERVENTIONS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_PERSONS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_ACTIVITIES TO BFS_ADMIN_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_PLAUSIERRORS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_FILTERS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_PLAUSIS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_EXPORTS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SSP_PARAMETERS TO BFS_ADMIN_ROLE; 

GRANT SELECT ON SBA_CONFIGDELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_SCHOOLS_CONFIGDELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_CANTONS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_DELIVERIES TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_INTERVENTIONS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_PERSONS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_QUALIFICATIONS TO BFS_ADMIN_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_PLAUSIERRORS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_FILTERS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_PLAUSIS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_EXPORTS TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SBA_PARAMETERS TO BFS_ADMIN_ROLE; 

GRANT SELECT ON MEBSEQ TO BFS_ADMIN_ROLE; 
GRANT SELECT ON SDLSEQ TO BFS_ADMIN_ROLE;
GRANT SELECT ON SSPSEQ TO BFS_ADMIN_ROLE;
GRANT SELECT ON SBASEQ TO BFS_ADMIN_ROLE;

GRANT SELECT ON V_SCHUL TO BFS_ADMIN_ROLE; 

COMMIT;