/****************************************************************************
 *	Stop in case of failure
 ****************************************************************************/
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

/****************************************************************************
 *	Reset Sequence
 ****************************************************************************/
COLUMN S new_val inc;

SELECT MEBSEQ.NEXTVAL S FROM dual;

ALTER SEQUENCE MEBSEQ INCREMENT BY -&inc MINVALUE 0;
SELECT MEBSEQ.NEXTVAL S FROM dual;

ALTER SEQUENCE MEBSEQ INCREMENT BY 1; 


/****************************************************************************
 *	PL/SQL
 ****************************************************************************/
DECLARE
  
BEGIN
	/*--------------------------  MEB_ROLE -------------------------------*/
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 0, 'de', 'RO', 'RO');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 1, 'de', 'DL', 'DL');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 2, 'de', 'DV', 'DV');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 3, 'de', 'EV', 'EV');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 4, 'de', 'EA', 'EA');
	
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 0, 'fr', 'RO', 'RO');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 1, 'fr', 'LD', 'LD');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 2, 'fr', 'RD', 'RD');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 3, 'fr', 'RR', 'RR');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 4, 'fr', 'AR', 'AR');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 0, 'it', 'RO', 'RO');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 1, 'it', 'DL', 'DL');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 2, 'it', 'DV', 'DV');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 3, 'it', 'EV', 'EV');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_ROLE', 4, 'it', 'EA', 'EA');


	/*--------------------------  MEB_PLAUSISTATUS ----------------------------*/
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 0, 'de', 'Undefiniert', 'Undefiniert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 1, 'de', 'Nicht plausibel', 'Nicht plausibel');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 2, 'de', 'Plausibel', 'Plausibel');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 3, 'de', 'Bestätigt', 'Bestätigt');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 0, 'fr', 'Indefini', 'Indefini');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 1, 'fr', 'Pas plausible', 'Pas plausible');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 2, 'fr', 'Plausible', 'Plausible');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 3, 'fr', 'Confirmé', 'Confirmé');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 0, 'it', 'Undefiniert', 'Undefiniert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 1, 'it', 'Nicht plausibel', 'Nicht plausibel');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 2, 'it', 'Plausibel', 'Plausibel');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSISTATUS', 3, 'it', 'Bestätigt', 'Bestätigt');

	/*--------------------------  MEB_CANTONSTATUS ----------------------------*/
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 0, 'de', 'Initialisiert', 'Initialisiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 4, 'de', 'Geliefert', 'Geliefert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 6, 'de', 'Validiert', 'Validiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 7, 'de', 'Finalisiert', 'Finalisiert');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 0, 'fr', 'Initialisé', 'Initialisé');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 4, 'fr', 'Livré', 'Livré');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 6, 'fr', 'Validé', 'Validé');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 7, 'fr', 'Finalisé', 'Finalisé');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 0, 'it', 'Initialisiert', 'Initialisiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 4, 'it', 'Geliefert', 'Geliefert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 6, 'it', 'Validiert', 'Validiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_CANTONSTATUS', 7, 'it', 'Finalisiert', 'Finalisiert');

	/*--------------------------  MEB_DELIVERYSTATUS ----------------------------*/
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 0, 'de', 'Initialisiert', 'Initialisiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 1, 'de', 'In Bearbeitung', 'In Bearbeitung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 2, 'de', 'Ersetzen/Ergänzen?', 'Ersetzen/Ergänzen?');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 3, 'de', 'Lieferbestätigung?', 'Lieferbestätigung?');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 4, 'de', 'Geliefert', 'Geliefert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 5, 'de', 'Prävalidiert', 'Prävalidiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 6, 'de', 'Validiert', 'Validiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 7, 'de', 'Finalisiert', 'Finalisiert');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 0, 'fr', 'Initialisié', 'Initialisié');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 1, 'fr', 'En cours', 'En cours');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 2, 'fr', 'Remplacer/Completer?', 'Remplacer/Completer?');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 3, 'fr', 'Confirmation livraison?', 'Confirmation livraison?');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 4, 'fr', 'Livrée', 'Livrée');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 5, 'fr', 'Prevalidé', 'Prevalidé');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 6, 'fr', 'Validé', 'Validé');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 7, 'fr', 'Finalisé', 'Finalisé');
	
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 0, 'it', 'Initialisiert', 'Initialisiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 1, 'it', 'In Bearbeitung', 'In Bearbeitung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 2, 'it', 'Ersetzen/Ergänzen?', 'Ersetzen/Ergänzen?');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 3, 'it', 'Lieferbestätigung?', 'Lieferbestätigung?');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 4, 'it', 'Geliefert', 'Geliefert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 5, 'it', 'Prävalidiert', 'Prävalidiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 6, 'it', 'Validiert', 'Validiert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DELIVERYSTATUS', 7, 'it', 'Finalisiert', 'Finalisiert');
	
	/*------------------------  MEB_INTERVENTIONTYPE -------------------------*/
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 0, 'de', 'Lieferung', 'Lieferung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 1, 'de', 'Lieferung', 'Fehlerhafte Lieferung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 2, 'de', 'Ergänzen', 'Ergänzen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 3, 'de', 'Ersetzen', 'Ersetzen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 4, 'de', 'Abbrechen', 'Abbrechen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 5, 'de', 'Bestätigen', 'Bestätigen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 6, 'de', 'Plausibilisieren', 'Plausibilisieren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 7, 'de', 'Prävalidieren', 'Prävalidieren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 8, 'de', 'Deprävalidieren', 'Prävalidierung zurücknehmen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 9, 'de', 'Validieren', 'Validieren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 10, 'de', 'Entvalidieren', 'Validierung zurücknehmen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 11, 'de', 'Finalisieren', 'Finalisieren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 12, 'de', 'Entfinalisieren', 'Finalisierung zurücknehmen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 13, 'de', 'Lieferung leeren', 'Lieferung leeren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 14, 'de', 'Letzten Datensatz löschen', 'Letzten Datensatz löschen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 15, 'de', 'Manuelle Intervention', 'Manuelle Intervention');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 16, 'de', 'Plausibericht in Erstellung', 'Plausibericht in Erstellung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
    	VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 17, 'de', 'Ignorierte Schule(n)', 'Ignorierte Schule(n)');
	
    INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 0, 'fr', 'Livraison', 'Livraison');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 1, 'fr', 'Livraison avec erreurs', 'Livraison avec erreurs');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 2, 'fr', 'Compléter', 'Compléter');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 3, 'fr', 'Remplacer', 'Remplacer');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 4, 'fr', 'Renoncer', 'Renoncer');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 5, 'fr', 'Confirmer', 'Confirmer');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 6, 'fr', 'Plausibiliser', 'Plausibiliser');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 7, 'fr', 'Prevalider', 'Prevalider');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 8, 'fr', 'Deprevalider', 'Deprevalider');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 9, 'fr', 'Valider', 'Valider');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 10, 'fr', 'Devalider', 'Devalider');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 11, 'fr', 'Finaliser', 'Finaliser');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 12, 'fr', 'Definaliser', 'Definaliser');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 13, 'fr', 'Effacer livraison', 'Effacer livraison');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 14, 'fr', 'Effacer dernier enregistrement', 'Effacer dernier enregistrement');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 15, 'fr', 'Intervention manuelle', 'Intervention manuelle');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 16, 'fr', 'Rapport de plausibilisation en création', 'Rapport de plausibilisation en création');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
   		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 17, 'fr', 'Écoles ignorées', 'Écoles ignorées');
		
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 0, 'it', 'Lieferung', 'Lieferung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 1, 'it', 'Fehlerhafte Lieferung', 'Fehlerhafte Lieferung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 2, 'it', 'Ergänzen', 'Ergänzen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 3, 'it', 'Ersetzen', 'Ersetzen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 4, 'it', 'Abbrechen', 'Abbrechen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 5, 'it', 'Bestätigen', 'Bestätigen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 6, 'it', 'Plausibilisieren', 'Plausibilisieren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 7, 'it', 'Prävalidieren', 'Prävalidieren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 8, 'it', 'Deprävalidieren', 'Prävalidierung zurücknehmen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 9, 'it', 'Validieren', 'Validieren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 10, 'it', 'Entvalidieren', 'Validierung zurücknehmen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 11, 'it', 'Finalisieren', 'Finalisieren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 12, 'it', 'Entfinalisieren', 'Finalisierung zurücknehmen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 13, 'it', 'Lieferung leeren', 'Lieferung leeren');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 14, 'it', 'Letzten Datensatz löschen', 'Letzten Datensatz löschen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 15, 'it', 'Manuelle Intervention', 'Manuelle Intervention');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 16, 'it', 'Plausibericht in Erstellung', 'Plausibericht in Erstellung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
    	VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 17, 'it', 'Ignorierte Schule(n)', 'Ignorierte Schule(n)');
		
	/*--------------------------  MEB_SYNCHSTATUS ----------------------------*/
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 0, 'de', 'Unverändert', 'Unverändert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 1, 'de', 'Geändert', 'Geändert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 2, 'de', 'Neu', 'Neu');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 3, 'de', 'Inaktiviert', 'Inaktiviert');
	
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 0, 'fr', 'Inchangé', 'Inchangé');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 1, 'fr', 'Changé', 'Changé');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 2, 'fr', 'Nouveau', 'Nouveau');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 3, 'fr', 'Inaktivé', 'Inaktivé');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 0, 'it', 'Unverändert', 'Unverändert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 1, 'it', 'Geändert', 'Geändert');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 2, 'it', 'Neu', 'Neu');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_SYNCHSTATUS', 3, 'it', 'Inaktiviert', 'Inaktiviert');

	/*--------------------------  MEB_PLAUSITYPE -------------------------------*/
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSITYPE', 0, 'de', 'Interne Plausi', 'Interne Plausi');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSITYPE', 1, 'de', 'Externe Plausi', 'Externe Plausi');
	
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSITYPE', 0, 'fr', 'Plausi Interne', 'Plausi Interne');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSITYPE', 1, 'fr', 'Plausi Externe', 'Plausi Externe');
	
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSITYPE', 0, 'it', 'Interne Plausi', 'Interne Plausi');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_PLAUSITYPE', 1, 'it', 'Externe Plausi', 'Externe Plausi');

	/*--------------------------  MEB_EXPORTTYPE -------------------------------*/
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 0, 'de', 'XML Export', 'XML Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 1, 'de', 'CSV Export', 'CSV Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 2, 'de', 'SAS Export', 'SAS Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 3, 'de', 'Export der Schulen', 'Export der Schulen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 10, 'de', 'Benutzerliste', 'Benutzerliste als Excel-File');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 11, 'de', 'Status der Initialisierung', 'Status der Initialisierung als Excel-File');
	
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 0, 'fr', 'XML Export', 'XML Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 1, 'fr', 'CSV Export', 'CSV Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 2, 'fr', 'SAS Export', 'SAS Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 3, 'fr', 'Export des écoles', 'Export des écoles');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 10, 'fr', 'Liste des utilisateurs' , 'Liste des utilisateurs');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 11, 'fr', 'Statut d''initialisation', 'Statut d''initialisation');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 0, 'it', 'XML Export', 'XML Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 1, 'it', 'CSV Export', 'CSV Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 2, 'it', 'SAS Export', 'SAS Export');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 3, 'it', 'Export der Schulen', 'Export der Schulen');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 10, 'it', 'Benutzerliste', 'Benutzerliste als Excel-File');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 11, 'it', 'Status der Initialisierung', 'Status der Initialisierung als Excel-File');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 20, 'de', 'XML Plausireport Lieferung', 'XML Plausireport für eine Lieferung');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 20, 'fr', 'XML rapport de plausibilisation livraison', 'XML rapport de plausibilisation de la livraison');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 20, 'it', 'XML Plausireport Lieferung', 'XML Plausireport für eine Lieferung');

	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 21, 'de', 'XML Plausireport Kanton', 'XML Plausireport für einen Kanton');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 21, 'fr', 'XML rapport de plausibilisation canton', 'XML rapport de plausibilisation du canton');
	INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_EXPORTTYPE', 21, 'it', 'XML Plausireport Kanton', 'XML Plausireport für einen Kanton');

	/*--------------------------  MEB_(DELIVERY)DATASTATUS -------------------------------*/
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 1, 'de', 'In Bearbeitung', 'In Bearbeitung');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 4, 'de', 'Geliefert', 'Geliefert');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 5, 'de', 'Prävalidiert', 'Prävalidiert');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 6, 'de', 'Validiert', 'Validiert');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 7, 'de', 'Finalisiert', 'Finalisiert');

	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 1, 'fr', 'En cours', 'En cours');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 4, 'fr', 'Livrée', 'Livrée');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 5, 'fr', 'Prevalidé', 'Prevalidé');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 6, 'fr', 'Validé', 'Validé');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 7, 'fr', 'Finalisé', 'Finalisé');

	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 1, 'it', 'In Bearbeitung', 'In Bearbeitung');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 4, 'it', 'Geliefert', 'Geliefert');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 5, 'it', 'Prävalidiert', 'Prävalidiert');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 6, 'it', 'Validiert', 'Validiert');
	INSERT INTO CODEGROUPs (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
		VALUES (MEBSEQ.NEXTVAL, 'MEB_DATASTATUS', 7, 'it', 'Finalisiert', 'Finalisiert');

END;
/


COMMIT;

