/* changed sequences to increment of 100 */
/* MEB */
select MEBSEQ.nextval from dual;
ALTER SEQUENCE MEBSEQ INCREMENT BY 100;

/* SBA */
select SBASEQ.nextval from dual;
ALTER SEQUENCE SBASEQ INCREMENT BY 100;

/* SBG */
select SBGSEQ.nextval from dual;
ALTER SEQUENCE SBGSEQ INCREMENT BY 100;

/* SDL */
select SDLSEQ.nextval from dual;
ALTER SEQUENCE SDLSEQ INCREMENT BY 100;

/* SSP */
select SSPSEQ.nextval from dual;
ALTER SEQUENCE SSPSEQ INCREMENT BY 100;


ALTER TABLE SCHOOLS ADD USERTEXT VARCHAR(252);


/******************************/
/* SBG Updates                */
/******************************/ 

/* Plausibericht als Job */
INSERT INTO CODEGROUP (CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT 'SBG_ACTIONTYPE', 12, 'de', 'in Erstellung', 'Plausibericht in Erstellung' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUP WHERE CODEGROUPID='SBG_ACTIONTYPE' AND CODE=12 AND LANGUAGE='de');

INSERT INTO CODEGROUP (CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT 'SBG_ACTIONTYPE', 12, 'fr', 'en création', 'Rapport de plausibilisation en création' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUP WHERE CODEGROUPID='SBG_ACTIONTYPE' AND CODE=12 AND LANGUAGE='fr');

/* ActVersion über Filter konfigurieren */
INSERT INTO CODEGROUP (CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT 'SBG_OBJECTTYPE', 7, 'de', 'Konfiguration', 'Konfiguration' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUP WHERE CODEGROUPID='SBG_OBJECTTYPE' AND CODE=7 AND LANGUAGE='de');

INSERT INTO CODEGROUP (CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT 'SBG_OBJECTTYPE', 7, 'fr', 'Configuration', 'Configuration' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUP WHERE CODEGROUPID='SBG_OBJECTTYPE' AND CODE=7 AND LANGUAGE='fr');

INSERT INTO FILTER (FILTERID, NAME_D, NAME_F, REFOBJECT, SOURCE, ISACTIVE, ISDEFAULT, AUTHORISATIONLEVEL)
SELECT SBGSEQ.NEXTVAL, 'ActVersion', 'ActVersion', 7, '2012', 1, 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT FILTERID FROM FILTER WHERE NAME_D='ActVersion' AND REFOBJECT=7);

/* neue Variablen */
PROMPT 'Bitte für Wert 1 DATA_TABLESPACE angeben:'
DEFINE DATA_TABLESPACE 	= &1;

PROMPT 'Bitte für Wert 2 INDEX_TABLESPACE angeben:'
DEFINE INDEX_TABLESPACE = &2;

/****************************************************************************
 *	Stop in case of failure
 ****************************************************************************/
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

CREATE TABLE SBG_KEYASPECT (
  -------------------------------------------------------------------------
  -- Attributes
  -------------------------------------------------------------------------
  KEYASPECTID    NUMBER,
  KEYASPECTCODE  NUMBER(3),
  PROFESSIONCODE NUMBER(10),	
	TEXT_DE        VARCHAR(100),
	TEXT_FR        VARCHAR(100),
  -------------------------------------------------------------------------
  -- Constraints
  -------------------------------------------------------------------------
  CONSTRAINT SBG_KEYASPECT_PK PRIMARY KEY (KEYASPECTID)
  USING INDEX
    PCTFREE    20
    INITRANS   2
    MAXTRANS   255
    TABLESPACE &INDEX_TABLESPACE
)
  TABLESPACE &DATA_TABLESPACE
  STORAGE	(INITIAL 1M NEXT 1M);

GRANT SELECT, UPDATE, INSERT, DELETE ON SBG_KEYASPECT TO SBG_APPL_ROL; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBG_KEYASPECT TO MEB_APPL_ROLE; 
GRANT SELECT ON SBG_KEYASPECT TO BFS_ADMIN_ROLE;

CREATE OR REPLACE PUBLIC SYNONYM SBG_KEYASPECT FOR SBG_KEYASPECT;

ALTER TABLE EVENT 
 ADD KEYASPECT NUMBER(3);

ALTER TABLE EVENT 
 ADD EDUCATIONYEAR NUMBER(2);
 
ALTER TABLE PERSON
 ADD NEWBIRTHDATE DATE;


/******************************/
/* MEB Tables                 */
/******************************/ 

/* SBA */
CREATE TABLE SBA_CANTONINTERVENTIONS (
  -------------------------------------------------------------------------
  -- Attributes
  -------------------------------------------------------------------------
	INTERVENTIONID     NUMBER,
	CANTONID           NUMBER,
	TYPE               NUMBER,
	INTERVENTION_USER  VARCHAR(50),
	INTERVENTION_DATE  DATE,
	PLAUSIREPORT_DE    BLOB,
	PLAUSIREPORT_FR    BLOB,
	PLAUSIREPORT_IT    BLOB,
	TEXT               VARCHAR(1000),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_CANTONINTERVENTIONS_PK PRIMARY KEY (INTERVENTIONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SBA_CINT_CAN_FK FOREIGN KEY (CANTONID) 
		REFERENCES SBA_CANTONS(CANTONID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_CINT_CAN_ID ON SBA_CANTONINTERVENTIONS(CANTONID)
      TABLESPACE &INDEX_TABLESPACE;
      
CREATE OR REPLACE PUBLIC SYNONYM SBA_CANTONINTERVENTIONS FOR SBA_CANTONINTERVENTIONS;

GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_CANTONINTERVENTIONS TO MEB_APPL_ROLE;
GRANT SELECT ON SBA_CANTONINTERVENTIONS TO BFS_ADMIN_ROLE;

/* SDL */
CREATE TABLE SDL_CANTONINTERVENTIONS (
  -------------------------------------------------------------------------
  -- Attributes
  -------------------------------------------------------------------------
	INTERVENTIONID     NUMBER,
	CANTONID           NUMBER,
	TYPE               NUMBER,
	INTERVENTION_USER  VARCHAR(50),
	INTERVENTION_DATE  DATE,
	PLAUSIREPORT_DE    BLOB,
	PLAUSIREPORT_FR    BLOB,
	PLAUSIREPORT_IT    BLOB,
	TEXT               VARCHAR(1000),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_CANTONINTERVENTIONS_PK PRIMARY KEY (INTERVENTIONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SDL_CINT_CAN_FK FOREIGN KEY (CANTONID) 
		REFERENCES SDL_CANTONS(CANTONID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_CINT_CAN_ID ON SDL_CANTONINTERVENTIONS(CANTONID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE OR REPLACE PUBLIC SYNONYM SDL_CANTONINTERVENTIONS FOR SDL_CANTONINTERVENTIONS;

GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_CANTONINTERVENTIONS TO MEB_APPL_ROLE;
GRANT SELECT ON SDL_CANTONINTERVENTIONS TO BFS_ADMIN_ROLE;

/* SSP */
CREATE TABLE SSP_CANTONINTERVENTIONS (
  -------------------------------------------------------------------------
  -- Attributes
  -------------------------------------------------------------------------
	INTERVENTIONID     NUMBER,
	CANTONID           NUMBER,
	TYPE               NUMBER,
	INTERVENTION_USER  VARCHAR(50),
	INTERVENTION_DATE  DATE,
	PLAUSIREPORT_DE    BLOB,
	PLAUSIREPORT_FR    BLOB,
	PLAUSIREPORT_IT    BLOB,
	TEXT               VARCHAR(1000),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_CANTONINTERVENTIONS_PK PRIMARY KEY (INTERVENTIONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SSP_CINT_CAN_FK FOREIGN KEY (CANTONID) 
		REFERENCES SSP_CANTONS(CANTONID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_CINT_CAN_ID ON SSP_CANTONINTERVENTIONS(CANTONID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE OR REPLACE PUBLIC SYNONYM SSP_CANTONINTERVENTIONS FOR SSP_CANTONINTERVENTIONS;

GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_CANTONINTERVENTIONS TO MEB_APPL_ROLE;
GRANT SELECT ON SSP_CANTONINTERVENTIONS TO BFS_ADMIN_ROLE;

/* MEB */
INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 0, 'de', 'Initialisieren', 'Initialisieren' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=0 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 0, 'it', 'Initialisieren', 'Initialisieren' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=0 AND LANGUAGE='it');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 0, 'fr', 'Initialiser', 'Initialiser' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=0 AND LANGUAGE='fr');


INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 1, 'de', 'Plausibilisieren', 'Plausibilisieren' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=1 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 1, 'it', 'Plausibilisieren', 'Plausibilisieren' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=1 AND LANGUAGE='it');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 1, 'fr', 'Plausibiliser', 'Plausibiliser' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=1 AND LANGUAGE='fr');


INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 2, 'de', 'Validieren', 'Validieren' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=2 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 2, 'it', 'Validieren', 'Validieren' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=2 AND LANGUAGE='it');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 2, 'fr', 'Valider', 'Valider' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=2 AND LANGUAGE='fr');


INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 3, 'de', 'Entvalidieren', 'Validierung zurücknehmen' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=3 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 3, 'it', 'Entvalidieren', 'Validierung zurücknehmen' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=3 AND LANGUAGE='it');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 3, 'fr', 'Devalider', 'Devalider' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=3 AND LANGUAGE='fr');


INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 4, 'de', 'Finalisieren', 'Finalisieren' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=4 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 4, 'it', 'Finalisieren', 'Finalisieren' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=4 AND LANGUAGE='it');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 4, 'fr', 'Finaliser', 'Finaliser' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=4 AND LANGUAGE='fr');


INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 5, 'de', 'Entfinalisieren', 'Finalisierung zurücknehmen' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=5 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 5, 'it', 'Entfinalisieren', 'Finalisierung zurücknehmen' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=5 AND LANGUAGE='it');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 5, 'fr', 'Definaliser', 'Definaliser' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=5 AND LANGUAGE='fr');


INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 15, 'de', 'Manuelle Intervention 1', 'Manuelle Intervention 1' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=15 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 15, 'it', 'Manuelle Intervention 1', 'Manuelle Intervention 1' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=15 AND LANGUAGE='it');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 15, 'fr', 'Intervention manuelle 1', 'Intervention manuelle 1' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=15 AND LANGUAGE='fr');


INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 16, 'de', 'Manuelle Intervention 2', 'Manuelle Intervention 2' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=16 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 16, 'it', 'Manuelle Intervention 2', 'Manuelle Intervention 2' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=16 AND LANGUAGE='it');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT MEBSEQ.NEXTVAL, 'MEB_CANTONINTTYPE', 16, 'fr', 'Intervention manuelle 2', 'Intervention manuelle 2' FROM DUAL
WHERE NOT EXISTS (SELECT CODEGROUPID, LANGUAGE FROM CODEGROUPS WHERE CODEGROUPID='MEB_CANTONINTTYPE' AND CODE=16 AND LANGUAGE='fr');


/* replace unique constraint for codegroups */
ALTER TABLE CODEGROUPS DROP constraint LOGICAL_KEY;
DROP INDEX LOGICAL_KEY;
CREATE UNIQUE INDEX LOGICAL_KEY ON CODEGROUPS (CODEGROUPID, CODE, LANGUAGE, VALIDFROMYEAR, CANTON) LOGGING TABLESPACE MEB_INDEX COMPUTE STATISTICS;
ALTER TABLE CODEGROUPS ADD (CONSTRAINT LOGICAL_KEY UNIQUE (CODEGROUPID, CODE, LANGUAGE, VALIDFROMYEAR, CANTON) USING INDEX LOGICAL_KEY ENABLE VALIDATE);


/* migrate plausireports from canton to canton intervention table */
-- SBA
-- create an initialize intervention for each canton
INSERT INTO SBA_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SBASEQ.NEXTVAL, CANTONID, 0, CREATION_USER, CREATION_DATE, null, null, null, null from SBA_CANTONS;
-- create a plausireport intervention for each canton containing a plausi report
INSERT INTO SBA_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SBASEQ.NEXTVAL, CANTONID, 1, PLAUSI_USER, PLAUSI_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, null from SBA_CANTONS where PLAUSIREPORT_DE is not null or PLAUSIREPORT_FR is not null or PLAUSIREPORT_IT is not null;
-- create a validate intervention for each validated canton
INSERT INTO SBA_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SBASEQ.NEXTVAL, CANTONID, 2, VALIDATION_USER, VALIDATION_DATE, null, null, null, null from SBA_CANTONS where VALIDATION_USER is not null;
-- create a finalize intervention for each finalized canton
INSERT INTO SBA_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SBASEQ.NEXTVAL, CANTONID, 4, FINALISATION_USER, FINALISATION_DATE, null, null, null, null from SBA_CANTONS where FINALISATION_USER is not null;
-- drop plausireport columns
ALTER TABLE SBA_CANTONS DROP COLUMN PLAUSIREPORT_DE;
ALTER TABLE SBA_CANTONS DROP COLUMN PLAUSIREPORT_FR;
ALTER TABLE SBA_CANTONS DROP COLUMN PLAUSIREPORT_IT;

-- SDL
-- create an initialize intervention for each canton
INSERT INTO SDL_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SDLSEQ.NEXTVAL, CANTONID, 0, CREATION_USER, CREATION_DATE, null, null, null, null from SDL_CANTONS;
-- create a plausireport intervention for each canton containing a plausi report
INSERT INTO SDL_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SDLSEQ.NEXTVAL, CANTONID, 1, PLAUSI_USER, PLAUSI_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, null from SDL_CANTONS where PLAUSIREPORT_DE is not null or PLAUSIREPORT_FR is not null or PLAUSIREPORT_IT is not null;
-- create a validate intervention for each validated canton
INSERT INTO SDL_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SDLSEQ.NEXTVAL, CANTONID, 2, VALIDATION_USER, VALIDATION_DATE, null, null, null, null from SDL_CANTONS where VALIDATION_USER is not null;
-- create a finalize intervention for each finalized canton
INSERT INTO SDL_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SDLSEQ.NEXTVAL, CANTONID, 4, FINALISATION_USER, FINALISATION_DATE, null, null, null, null from SDL_CANTONS where FINALISATION_USER is not null;
-- drop plausireport columns
ALTER TABLE SDL_CANTONS DROP COLUMN PLAUSIREPORT_DE;
ALTER TABLE SDL_CANTONS DROP COLUMN PLAUSIREPORT_FR;
ALTER TABLE SDL_CANTONS DROP COLUMN PLAUSIREPORT_IT;

-- SSP
-- create an initialize intervention for each canton
INSERT INTO SSP_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SSPSEQ.NEXTVAL, CANTONID, 0, CREATION_USER, CREATION_DATE, null, null, null, null from SSP_CANTONS;
-- create a plausireport intervention for each canton containing a plausi report
INSERT INTO SSP_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SSPSEQ.NEXTVAL, CANTONID, 1, PLAUSI_USER, PLAUSI_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, null from SSP_CANTONS where PLAUSIREPORT_DE is not null or PLAUSIREPORT_FR is not null or PLAUSIREPORT_IT is not null;
-- create a validate intervention for each validated canton
INSERT INTO SSP_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SSPSEQ.NEXTVAL, CANTONID, 2, VALIDATION_USER, VALIDATION_DATE, null, null, null, null from SSP_CANTONS where VALIDATION_USER is not null;
-- create a finalize intervention for each finalized canton
INSERT INTO SSP_CANTONINTERVENTIONS (INTERVENTIONID, CANTONID, TYPE, INTERVENTION_USER, INTERVENTION_DATE, PLAUSIREPORT_DE, PLAUSIREPORT_FR, PLAUSIREPORT_IT, TEXT) 
SELECT SSPSEQ.NEXTVAL, CANTONID, 4, FINALISATION_USER, FINALISATION_DATE, null, null, null, null from SSP_CANTONS where FINALISATION_USER is not null;
-- drop plausireport columns
ALTER TABLE SSP_CANTONS DROP COLUMN PLAUSIREPORT_DE;
ALTER TABLE SSP_CANTONS DROP COLUMN PLAUSIREPORT_FR;
ALTER TABLE SSP_CANTONS DROP COLUMN PLAUSIREPORT_IT;

COMMIT;