
/* MEB */
INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
    VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 17, 'de', 'Ignorierte Schule(n)', 'Ignorierte Schule(n)');
INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
    VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 17, 'fr', 'Écoles ignorées', 'Écoles ignorées');
INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
    VALUES (MEBSEQ.NEXTVAL, 'MEB_INTERVENTIONTYPE', 17, 'it', 'Ignorierte Schule(n)', 'Ignorierte Schule(n)');

/* SDL */
ALTER TABLE SDL_PLAUSIERRORS MODIFY ERRORMSG_DE VARCHAR(500);
ALTER TABLE SDL_PLAUSIERRORS MODIFY ERRORMSG_FR VARCHAR(500);
ALTER TABLE SDL_PLAUSIERRORS MODIFY ERRORMSG_IT VARCHAR(500);

ALTER TABLE SDL_PLAUSIS DROP CONSTRAINT SDL_PLAUSIS_UNIQUE_ID;


/* SSP */
ALTER TABLE SSP_PLAUSIERRORS MODIFY ERRORMSG_DE VARCHAR(500);
ALTER TABLE SSP_PLAUSIERRORS MODIFY ERRORMSG_FR VARCHAR(500);
ALTER TABLE SSP_PLAUSIERRORS MODIFY ERRORMSG_IT VARCHAR(500);

ALTER TABLE SSP_ACTIVITIES MODIFY PENSUM NUMBER(6,2);
ALTER TABLE SSP_ACTIVITIES MODIFY FULLTIMEREF NUMBER(6,2);

ALTER TABLE SSP_PLAUSIS DROP CONSTRAINT SSP_PLAUSIS_UNIQUE_ID;


/* SBA */
ALTER TABLE SBA_PLAUSIERRORS MODIFY ERRORMSG_DE VARCHAR(500);
ALTER TABLE SBA_PLAUSIERRORS MODIFY ERRORMSG_FR VARCHAR(500);
ALTER TABLE SBA_PLAUSIERRORS MODIFY ERRORMSG_IT VARCHAR(500);

ALTER TABLE SBA_PLAUSIS DROP CONSTRAINT SBA_PLAUSIS_UNIQUE_ID;
