/* SSP */
/* mantis 2021 */
ALTER TABLE SSP_ACTIVITIES MODIFY PENSUM NUMBER(7,3);
ALTER TABLE SSP_ACTIVITIES MODIFY FULLTIMEREF NUMBER(7,3);


/* mantis 2067 */
/* SDL */
INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SDLSEQ.NEXTVAL, 'SDL_OBJECTTYPE', 7, 'de', 'Konfiguration', 'Konfiguration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SDL_OBJECTTYPE' AND CODE=7 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SDLSEQ.NEXTVAL, 'SDL_OBJECTTYPE', 7, 'fr', 'Configuration', 'Configuration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SDL_OBJECTTYPE' AND CODE=7 AND LANGUAGE='fr');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SDLSEQ.NEXTVAL, 'SDL_OBJECTTYPE', 7, 'it', 'Konfiguration', 'Konfiguration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SDL_OBJECTTYPE' AND CODE=7 AND LANGUAGE='it');

INSERT INTO SDL_FILTERS (FILTERID, NAME_DE, NAME_FR, NAME_IT, REFOBJECT, SOURCE, ISACTIVE, ISDEFAULT, AUTHORISATIONLEVEL)
SELECT SDLSEQ.NEXTVAL, 'ActVersion', 'ActVersion', 'ActVersion', 7, '2012', 1, 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT FILTERID FROM SDL_FILTERS WHERE NAME_DE='ActVersion' AND REFOBJECT=7);

INSERT INTO SDL_FILTERS (FILTERID, NAME_DE, NAME_FR, NAME_IT, REFOBJECT, SOURCE, ISACTIVE, ISDEFAULT, AUTHORISATIONLEVEL)
SELECT SDLSEQ.NEXTVAL, 'InitVersion', 'InitVersion', 'InitVersion', 7, '2012', 1, 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT FILTERID FROM SDL_FILTERS WHERE NAME_DE='InitVersion' AND REFOBJECT=7);

/* SSP */
INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SSPSEQ.NEXTVAL, 'SSP_OBJECTTYPE', 7, 'de', 'Konfiguration', 'Konfiguration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SSP_OBJECTTYPE' AND CODE=7 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SSPSEQ.NEXTVAL, 'SSP_OBJECTTYPE', 7, 'fr', 'Configuration', 'Configuration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SSP_OBJECTTYPE' AND CODE=7 AND LANGUAGE='fr');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SSPSEQ.NEXTVAL, 'SSP_OBJECTTYPE', 7, 'it', 'Konfiguration', 'Konfiguration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SSP_OBJECTTYPE' AND CODE=7 AND LANGUAGE='it');

INSERT INTO SSP_FILTERS (FILTERID, NAME_DE, NAME_FR, NAME_IT, REFOBJECT, SOURCE, ISACTIVE, ISDEFAULT, AUTHORISATIONLEVEL)
SELECT SSPSEQ.NEXTVAL, 'ActVersion', 'ActVersion', 'ActVersion', 7, '2012', 1, 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT FILTERID FROM SSP_FILTERS WHERE NAME_DE='ActVersion' AND REFOBJECT=7);

INSERT INTO SSP_FILTERS (FILTERID, NAME_DE, NAME_FR, NAME_IT, REFOBJECT, SOURCE, ISACTIVE, ISDEFAULT, AUTHORISATIONLEVEL)
SELECT SSPSEQ.NEXTVAL, 'InitVersion', 'InitVersion', 'InitVersion', 7, '2012', 1, 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT FILTERID FROM SSP_FILTERS WHERE NAME_DE='InitVersion' AND REFOBJECT=7);

/* SBA */
INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SBASEQ.NEXTVAL, 'SBA_OBJECTTYPE', 7, 'de', 'Konfiguration', 'Konfiguration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SBA_OBJECTTYPE' AND CODE=7 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SBASEQ.NEXTVAL, 'SBA_OBJECTTYPE', 7, 'fr', 'Configuration', 'Configuration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SBA_OBJECTTYPE' AND CODE=7 AND LANGUAGE='fr');

INSERT INTO CODEGROUPS (ID, CODEGROUPID, CODE, LANGUAGE, CODETEXTABBR, CODETEXT)
SELECT SBASEQ.NEXTVAL, 'SBA_OBJECTTYPE', 7, 'it', 'Konfiguration', 'Konfiguration' FROM DUAL
WHERE NOT EXISTS (SELECT ID FROM CODEGROUPS WHERE CODEGROUPID='SBA_OBJECTTYPE' AND CODE=7 AND LANGUAGE='it');

INSERT INTO SBA_FILTERS (FILTERID, NAME_DE, NAME_FR, NAME_IT, REFOBJECT, SOURCE, ISACTIVE, ISDEFAULT, AUTHORISATIONLEVEL)
SELECT SBASEQ.NEXTVAL, 'ActVersion', 'ActVersion', 'ActVersion', 7, '2012', 1, 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT FILTERID FROM SBA_FILTERS WHERE NAME_DE='ActVersion' AND REFOBJECT=7);

INSERT INTO SBA_FILTERS (FILTERID, NAME_DE, NAME_FR, NAME_IT, REFOBJECT, SOURCE, ISACTIVE, ISDEFAULT, AUTHORISATIONLEVEL)
SELECT SBASEQ.NEXTVAL, 'InitVersion', 'InitVersion', 'InitVersion', 7, '2012', 1, 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT FILTERID FROM SBA_FILTERS WHERE NAME_DE='InitVersion' AND REFOBJECT=7);
