set time on
set timing on
set trimspool on
set echo on

/* neue Variablen */
accept DATA_TABLESPACE prompt 'Bitte Wert für DATEN TABLESPACE angeben: '
accept INDEX_TABLESPACE prompt 'Bitte Wert für INDEX TABLESPACE angeben: '

/******************************/
/* SBG Updates                */
/******************************/ 

DELETE FROM PLAUSIERROR pe WHERE NOT EXISTS (SELECT * FROM PERSON p WHERE p.PID = pe.PID) AND pe.PID IS NOT NULL;
ALTER TABLE PLAUSIERROR ADD (CONSTRAINT PLAUSIERROR_PID_FK FOREIGN KEY (PID) REFERENCES PERSON(PID) ON DELETE CASCADE ENABLE VALIDATE);

DELETE FROM PLAUSIERROR pe WHERE NOT EXISTS (SELECT * FROM EVENT e WHERE e.EVENTID = pe.EVENTID) AND pe.EVENTID IS NOT NULL;
ALTER TABLE PLAUSIERROR ADD (CONSTRAINT PLAUSIERROR_EVENTID_FK FOREIGN KEY (EVENTID) REFERENCES EVENT(EVENTID) ON DELETE CASCADE ENABLE VALIDATE);

DELETE FROM PLAUSIERROR pe WHERE NOT EXISTS (SELECT * FROM MACRO m WHERE m.MACROID = pe.MACROID) AND pe.MACROID IS NOT NULL;
ALTER TABLE PLAUSIERROR ADD (CONSTRAINT PLAUSIERROR_MACROID_FK FOREIGN KEY (MACROID) REFERENCES MACRO(MACROID) ON DELETE CASCADE ENABLE VALIDATE);

ALTER TABLE PLAUSIERROR MODIFY DELIVERYID NOT NULL;

DELETE FROM EVENT e WHERE NOT EXISTS (SELECT * FROM PERSON p WHERE p.PID = e.PID) AND e.PID IS NOT NULL;
ALTER TABLE EVENT ADD (CONSTRAINT EVENT_PID_FK FOREIGN KEY (PID) REFERENCES PERSON(PID) ON DELETE CASCADE ENABLE VALIDATE);

ALTER TABLE EVENT MODIFY PID NOT NULL;

ALTER TABLE PERSON MODIFY DELIVERYID NOT NULL;

ALTER TABLE ACTION MODIFY DELIVERYID NOT NULL;

ALTER TABLE DELIVERY MODIFY CANTON NOT NULL;
ALTER TABLE DELIVERY MODIFY VERSION NOT NULL;


/******************************/
/* SBA Updates                */
/******************************/ 

ALTER TABLE SBA_CANTONS MODIFY CANTON NOT NULL;
ALTER TABLE SBA_CANTONS MODIFY VERSION NOT NULL;
CREATE UNIQUE INDEX SBA_CANTONS_LOGICAL_KEY ON SBA_CANTONS (CANTON, VERSION) LOGGING TABLESPACE &INDEX_TABLESPACE COMPUTE STATISTICS;
ALTER TABLE SBA_CANTONS ADD (CONSTRAINT SBA_CANTONS_LOGICAL_KEY UNIQUE (CANTON, VERSION) USING INDEX SBA_CANTONS_LOGICAL_KEY ENABLE VALIDATE);

/******************************/
/* SDL Updates                */
/******************************/ 

ALTER TABLE SDL_CANTONS MODIFY CANTON NOT NULL;
ALTER TABLE SDL_CANTONS MODIFY VERSION NOT NULL;
CREATE UNIQUE INDEX SDL_CANTONS_LOGICAL_KEY ON SDL_CANTONS (CANTON, VERSION) LOGGING TABLESPACE &INDEX_TABLESPACE COMPUTE STATISTICS;
ALTER TABLE SDL_CANTONS ADD (CONSTRAINT SDL_CANTONS_LOGICAL_KEY UNIQUE (CANTON, VERSION) USING INDEX SDL_CANTONS_LOGICAL_KEY ENABLE VALIDATE);

/******************************/
/* SSP Updates                */
/******************************/ 

ALTER TABLE SSP_CANTONS MODIFY CANTON NOT NULL;
ALTER TABLE SSP_CANTONS MODIFY VERSION NOT NULL;
CREATE UNIQUE INDEX SSP_CANTON_LOGICAL_KEY ON SSP_CANTONS (CANTON, VERSION) LOGGING TABLESPACE &INDEX_TABLESPACE COMPUTE STATISTICS;
ALTER TABLE SSP_CANTONS ADD (CONSTRAINT SSP_CANTON_LOGICAL_KEY UNIQUE (CANTON, VERSION) USING INDEX SSP_CANTON_LOGICAL_KEY ENABLE VALIDATE);





