
/* SDL */
ALTER TABLE SDL_CANTONS 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SDL_DELIVERIES 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SDL_SCHOOLS 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SDL_CLASSES 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SDL_LEARNERS 
 ADD CONFIRMRULES VARCHAR2(128);

ALTER TABLE SDL_PLAUSIS 
 ADD ID VARCHAR2(20);
ALTER TABLE SDL_PLAUSIS 
 ADD CONSTRAINT SDL_PLAUSIS_UNIQUE_ID UNIQUE(ID);
ALTER TABLE SDL_EXPORTS 
 ADD ID VARCHAR2(20);
ALTER TABLE SDL_EXPORTS 
 ADD CONSTRAINT SDL_EXPORTS_UNIQUE_ID UNIQUE(ID);

/* SSP */
ALTER TABLE SSP_CANTONS 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SSP_DELIVERIES 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SSP_PERSONS 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SSP_ACTIVITIES 
 ADD CONFIRMRULES VARCHAR2(128);

ALTER TABLE SSP_PLAUSIS 
 ADD ID VARCHAR2(20);
ALTER TABLE SSP_PLAUSIS 
 ADD CONSTRAINT SSP_PLAUSIS_UNIQUE_ID UNIQUE(ID);
ALTER TABLE SSP_EXPORTS
 ADD ID VARCHAR2(20);
ALTER TABLE SSP_EXPORTS 
 ADD CONSTRAINT SSP_EXPORTS_UNIQUE_ID UNIQUE(ID);

/* SBA */
ALTER TABLE SBA_CANTONS 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SBA_DELIVERIES 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SBA_PERSONS 
 ADD CONFIRMRULES VARCHAR2(128);
ALTER TABLE SBA_QUALIFICATIONS 
 ADD CONFIRMRULES VARCHAR2(128);

ALTER TABLE SBA_PLAUSIS 
 ADD ID VARCHAR2(20);
ALTER TABLE SBA_PLAUSIS 
 ADD CONSTRAINT SBA_PLAUSIS_UNIQUE_ID UNIQUE(ID);
ALTER TABLE SBA_EXPORTS
 ADD ID VARCHAR2(20);
ALTER TABLE SBA_EXPORTS 
 ADD CONSTRAINT SBA_EXPORTS_UNIQUE_ID UNIQUE(ID);
