
/* MEB */

CREATE INDEX SCHOOLS_CANTONALCODE_SDL ON SCHOOLS(CANTONALCODE_SDL)
	TABLESPACE MEB_INDEX;
CREATE INDEX SCHOOLS_CANTONALCODE_SSP ON SCHOOLS(CANTONALCODE_SSP)
	TABLESPACE MEB_INDEX;
CREATE INDEX SCHOOLS_CANTONALCODE_SBA ON SCHOOLS(CANTONALCODE_SBA)
	TABLESPACE MEB_INDEX;
	
/* SSP */
CREATE INDEX SSP_PERSONS_ID ON SSP_PERSONS(ID)
    TABLESPACE MEB_INDEX;
  
/* SBA */
CREATE INDEX SBA_PERSONS_ID ON SBA_PERSONS(ID) 
	TABLESPACE MEB_INDEX;
  
/* SBG */
CREATE INDEX PERSON_VERSION ON PERSON(VERSION) 
	TABLESPACE MEB_INDEX;
CREATE INDEX PERSON_CANTON ON PERSON(CANTON) 
	TABLESPACE MEB_INDEX;
CREATE INDEX EVENT_VERSION ON EVENT(VERSION) 
	TABLESPACE MEB_INDEX;
CREATE INDEX EVENT_CANTON ON EVENT(CANTON) 
	TABLESPACE MEB_INDEX;
CREATE INDEX PLAUSIERROR_PID ON PLAUSIERROR(PID) 
	TABLESPACE MEB_INDEX;
CREATE INDEX PLAUSIERROR_EVENTID ON PLAUSIERROR(EVENTID) 
	TABLESPACE MEB_INDEX;
