WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

GRANT SELECT, UPDATE, INSERT, DELETE ON BATCH_JOB_EXECUTION TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON BATCH_JOB_EXECUTION_CONTEXT TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON BATCH_JOB_INSTANCE TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON BATCH_JOB_PARAMS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON BATCH_STEP_EXECUTION TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON BATCH_STEP_EXECUTION_CONTEXT TO MEB_APPL_ROLE; 

GRANT SELECT ON BATCH_STEP_EXECUTION_SEQ TO MEB_APPL_ROLE; 
GRANT SELECT ON BATCH_JOB_EXECUTION_SEQ TO MEB_APPL_ROLE;
GRANT SELECT ON BATCH_JOB_SEQ TO MEB_APPL_ROLE;


GRANT SELECT, UPDATE, INSERT, DELETE ON CODEGROUPS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCHOOLS TO MEB_APPL_ROLE; 
GRANT SELECT ON V_SCHUL TO MEB_APPL_ROLE; 

GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_CONFIGDELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_SCHOOLS_CONFIGDELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_CANTONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_DELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_INTERVENTIONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_SCHOOLS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_CLASSES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_LEARNERS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_PLAUSIERRORS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_FILTERS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_PLAUSIS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_EXPORTS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_PARAMETERS TO MEB_APPL_ROLE; 

GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_CONFIGDELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_SCHOOLS_CONFIGDELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_CANTONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_DELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_INTERVENTIONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_PERSONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_ACTIVITIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_PLAUSIERRORS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_FILTERS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_PLAUSIS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_EXPORTS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SSP_PARAMETERS TO MEB_APPL_ROLE; 

GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_CONFIGDELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_SCHOOLS_CONFIGDELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_CANTONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_DELIVERIES TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_INTERVENTIONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_PERSONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_QUALIFICATIONS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_PLAUSIERRORS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_FILTERS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_PLAUSIS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_EXPORTS TO MEB_APPL_ROLE; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SBA_PARAMETERS TO MEB_APPL_ROLE; 


GRANT SELECT ON MEBSEQ TO MEB_APPL_ROLE; 
GRANT SELECT ON SDLSEQ TO MEB_APPL_ROLE;
GRANT SELECT ON SSPSEQ TO MEB_APPL_ROLE;
GRANT SELECT ON SBASEQ TO MEB_APPL_ROLE;
GRANT SELECT ON SBGSEQ TO MEB_APPL_ROLE;

COMMIT;

