PROMPT 'Bitte für Wert 1 DATA_TABLESPACE angeben:'
DEFINE DATA_TABLESPACE 	= &1;

PROMPT 'Bitte für Wert 2 INDEX_TABLESPACE angeben:'
DEFINE INDEX_TABLESPACE = &2;

/****************************************************************************
 *	Stop in case of failure
 ****************************************************************************/
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

/****************************************************************************
 *	Create SBA Admin Tables
 ****************************************************************************/
CREATE TABLE SBA_FILTERS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	FILTERID		NUMBER,
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	REFOBJECT		NUMBER(2),
	SOURCE			VARCHAR(1020),
	AUTHORISATIONLEVEL	NUMBER(2),	
	ISACTIVE		NUMBER(1),
	ISDEFAULT		NUMBER(1),
	FILTERORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_FILTERS_PK PRIMARY KEY (FILTERID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);


CREATE TABLE SBA_PLAUSIS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	PLAUSIID		NUMBER,
	TYPE			NUMBER(2),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	SOURCE			VARCHAR(1020),
	OBJECTLEVEL		NUMBER(2),
	AUTHORISATIONLEVEL	NUMBER(2),
	ISACTIVE		NUMBER(1),
	ISCONFIRMABLE		NUMBER(1),
	VALIDFROM		NUMBER(4),
	VALIDTO			NUMBER(4),			
	PLAUSIORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_PLAUSIS_PK PRIMARY KEY (PLAUSIID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE TABLE SBA_EXPORTS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	EXPORTID		NUMBER,
	TYPE			NUMBER(2),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	SOURCE			VARCHAR(1020),
	AUTHORISATIONLEVEL	NUMBER(2),
	ISACTIVE		NUMBER(1),	
	EXPORTORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_EXPORTS_PK PRIMARY KEY (EXPORTID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

	
CREATE TABLE SBA_PARAMETERS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	PARAMETERID		NUMBER,
	FILTERID		NUMBER,
	PLAUSIID		NUMBER,
	EXPORTID		NUMBER,
	UNIQUENAME		VARCHAR(20),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DEFAULTVALUE		VARCHAR(60),
	PARAMETERORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_PARAMETERS_PK PRIMARY KEY (PARAMETERID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SBA_PARAMETERS_FILTER_FK FOREIGN KEY (FILTERID) 
		REFERENCES SBA_FILTERS(FILTERID)
		ON DELETE CASCADE,
	CONSTRAINT SBA_PARAMETERS_PLAUSI_FK FOREIGN KEY (PLAUSIID) 
		REFERENCES SBA_PLAUSIS(PLAUSIID)
		ON DELETE CASCADE,
	CONSTRAINT SBA_PARAMETERS_EXPORT_FK FOREIGN KEY (EXPORTID) 
		REFERENCES SBA_EXPORTS(EXPORTID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_PARAMETERS_FILTERS_ID ON SBA_PARAMETERS(FILTERID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PARAMETERS_PLAUSIS_ID ON SBA_PARAMETERS(PLAUSIID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PARAMETERS_EXPORTS_ID ON SBA_PARAMETERS(EXPORTID)
      TABLESPACE &INDEX_TABLESPACE;

/****************************************************************************
 *	Create SBA Init Tables
 ****************************************************************************/

CREATE TABLE SBA_CANTONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	CANTONID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	PLAUSI_USER		VARCHAR(50),
	PLAUSI_DATE		DATE,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	FINALISATION_USER	VARCHAR(50),
	FINALISATION_DATE	DATE,
	PLAUSIREPORT_DE		BLOB,
	PLAUSIREPORT_FR		BLOB,
	PLAUSIREPORT_IT		BLOB,
	USERTEXT		VARCHAR(252),		
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_CANTONS_PK PRIMARY KEY (CANTONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE TABLE SBA_CONFIGDELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	DELIVERYID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	ISDEFAULT		NUMBER(1),
	DL_USERS		VARCHAR(500),
	RO_USERS		VARCHAR(500),
	REFERENCEDATE		DATE,
	DUEDATE			DATE,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	USERTEXT		VARCHAR(252),		
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_CONFIGDELIVERIES_PK PRIMARY KEY (DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_CONFIGDELIVERIES_ID ON SBA_CONFIGDELIVERIES(CANTON, VERSION, DELIVERYCODE)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_CFGDEL_DELIVERYCODE ON SBA_CONFIGDELIVERIES(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;

CREATE TABLE SBA_SCHOOLS_CONFIGDELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	SCHOOLID		NUMBER,
	DELIVERYID		NUMBER,
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_SCHOOLS_CONFIGDELIVERY_PK PRIMARY KEY (SCHOOLID, DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SBA_SC_SCHOOLS_FK FOREIGN KEY (SCHOOLID) 
		REFERENCES SCHOOLS(SCHOOLID)
		ON DELETE CASCADE,
	CONSTRAINT SBA_SC_CONFIGDELIVERIES_FK FOREIGN KEY (DELIVERYID)
  		REFERENCES SBA_CONFIGDELIVERIES(DELIVERYID)
 		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_SCHOOLS_CF_SCHOOLID ON SBA_SCHOOLS_CONFIGDELIVERIES(SCHOOLID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_SCHOOLS_CF_DELIVERYID ON SBA_SCHOOLS_CONFIGDELIVERIES(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

/****************************************************************************
 *	Create SBA DATA Tables
 ****************************************************************************/

CREATE TABLE SBA_DELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	DELIVERYID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	DELIVERYDATE		DATE,
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(252),
	ISLOCKED		NUMBER(1),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_DELIVERIES_PK PRIMARY KEY (DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_DELIVERIES_ID ON SBA_DELIVERIES(CANTON, VERSION, DELIVERYCODE)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_DELIVERIES_CFGDELCODE ON SBA_DELIVERIES(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;

CREATE TABLE SBA_INTERVENTIONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	INTERVENTIONID		NUMBER,
	DELIVERYID		NUMBER,
	TYPE			NUMBER,
	INTERVENTION_USER	VARCHAR(50),
	INTERVENTION_DATE 	DATE,
	PLAUSIREPORT_DE		BLOB,
	PLAUSIREPORT_FR		BLOB,
	PLAUSIREPORT_IT		BLOB,
	DELIVERYFILE		BLOB,
	REPORT_DE		VARCHAR(1000),
	REPORT_FR		VARCHAR(1000),
	REPORT_IT		VARCHAR(1000),
	TEXT			VARCHAR(1000),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_INTERVENTIONS_PK PRIMARY KEY (INTERVENTIONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SBA_INTERVENTION_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SBA_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_INT_DEL_ID ON SBA_INTERVENTIONS(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE TABLE SBA_PERSONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	PERSONID		NUMBER,
	DELIVERYID		NUMBER,
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	IDTYPE			VARCHAR(20),
	ID			VARCHAR(20),
	SEX			NUMBER(1),
	BIRTHDATE		DATE,
	RESIDENCE		NUMBER(4),
	HISTORIC_RESIDENCE	NUMBER(5),
	COUNTRY		NUMBER(4),
	ORIGDELIVERYDATA	VARCHAR(4000),
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(256),
	ISTODELETE		NUMBER(1),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_PERSONS_PK PRIMARY KEY (PERSONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SBA_PERSONS_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SBA_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_PERSONS_DELIVERIES_ID ON SBA_PERSONS(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE INDEX SBA_PERSONS_CANTON ON SBA_PERSONS(CANTON)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PERSONS_VERSION ON SBA_PERSONS(VERSION)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PERSONS_DELIVERYCODE ON SBA_PERSONS(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PERSONS_CFGDELCODE ON SBA_PERSONS(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PERSONS_PLAUSISTATUS ON SBA_PERSONS(PLAUSISTATUS)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PERSONS_ID ON SBA_PERSONS(ID)
      TABLESPACE &INDEX_TABLESPACE;


CREATE TABLE SBA_QUALIFICATIONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	QUALIFICATIONID		NUMBER,
	PERSONID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	SCHOOLIDTYPE		VARCHAR(20),
	SCHOOLID			VARCHAR(20),
	EDUCATIONTYPE		NUMBER(15),
	EXAMTYPE			NUMBER(1),
	EXAMDATE			DATE,
	EXAMNR				NUMBER(1),
	RESULT				NUMBER(1),
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(256),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_QUALIFICATIONS_PK PRIMARY KEY (QUALIFICATIONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SBA_QUALIFICATIONS_PERSON_FK FOREIGN KEY (PERSONID) 
		REFERENCES SBA_PERSONS(PERSONID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_QUALI_PERSONS_ID ON SBA_QUALIFICATIONS(PERSONID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE INDEX SBA_QUALI_CANTON ON SBA_QUALIFICATIONS(CANTON)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_QUALI_VERSION ON SBA_QUALIFICATIONS(VERSION)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_QUALI_DELIVERYCODE ON SBA_QUALIFICATIONS(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_QUALI_CFGDELCODE ON SBA_QUALIFICATIONS(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;


CREATE TABLE SBA_PLAUSIERRORS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	ERRORID			NUMBER,
	CANTONID		NUMBER,
	DELIVERYID		NUMBER,
	PERSONID		NUMBER,
	QUALIFICATIONID		NUMBER,
	PLAUSIID		NUMBER,
	ERRORMSG_DE		VARCHAR(500),
	ERRORMSG_FR		VARCHAR(500),
	ERRORMSG_IT		VARCHAR(500),
	REPORTDATA		VARCHAR(1000),
	ISCONFIRMED		NUMBER(1),
	CONFIRMID		VARCHAR(50),
	ISTODELETE		NUMBER(1),
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,	
	USERTEXT		VARCHAR(252),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SBA_PLAUSIERRORS_PK PRIMARY KEY (ERRORID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SBA_PLAUSIERRORS_CANTON_FK FOREIGN KEY (CANTONID) 
		REFERENCES SBA_CANTONS(CANTONID)
		ON DELETE CASCADE,
	CONSTRAINT SBA_PLAUSIERRORS_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SBA_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE,
	CONSTRAINT SBA_PLAUSIERRORS_PERSON_FK FOREIGN KEY (PERSONID) 
		REFERENCES SBA_PERSONS(PERSONID)
		ON DELETE CASCADE,
	CONSTRAINT SBA_PLAUSIERRORS_QUALI_FK FOREIGN KEY (QUALIFICATIONID) 
		REFERENCES SBA_QUALIFICATIONS(QUALIFICATIONID)
		ON DELETE CASCADE,
	CONSTRAINT SBA_PLAUSIERRORS_PLAUSI_FK FOREIGN KEY (PLAUSIID) 
		REFERENCES SBA_PLAUSIS(PLAUSIID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SBA_PLAUSIERROR_DELIVERY on SBA_PLAUSIERRORS(DELIVERYID)
  tablespace &INDEX_TABLESPACE
  pctfree  20
  initrans 2
  maxtrans 255;

CREATE INDEX SBA_PLAUSIERRORS_CANTONS_ID ON SBA_PLAUSIERRORS(CANTONID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PLAUSIERRORS_PERSONS_ID ON SBA_PLAUSIERRORS(PERSONID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PLAUSIERRORS_QUALI_ID ON SBA_PLAUSIERRORS(QUALIFICATIONID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PLAUSIERRORS_PLAUSIS_ID ON SBA_PLAUSIERRORS(PLAUSIID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SBA_PLAUSIERRORS_DELIV_PERSON ON SBA_PLAUSIERRORS(DELIVERYID, PERSONID)
      TABLESPACE &INDEX_TABLESPACE;


/****************************************************************************
 *	Create SBA Sequence
 ****************************************************************************/
CREATE SEQUENCE SBASEQ;

/****************************************************************************
 *	Create Synonyms
 ****************************************************************************/
CREATE OR REPLACE PUBLIC SYNONYM SBA_CANTONS FOR SBA_CANTONS;
CREATE OR REPLACE PUBLIC SYNONYM SBA_CONFIGDELIVERIES FOR SBA_CONFIGDELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SBA_SCHOOLS_CONFIGDELIVERIES FOR SBA_SCHOOLS_CONFIGDELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SBA_DELIVERIES FOR SBA_DELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SBA_INTERVENTIONS FOR SBA_INTERVENTIONS;
CREATE OR REPLACE PUBLIC SYNONYM SBA_PERSONS FOR SBA_PERSONS;
CREATE OR REPLACE PUBLIC SYNONYM SBA_QUALIFICATIONS FOR SBA_QUALIFICATIONS;
CREATE OR REPLACE PUBLIC SYNONYM SBA_PLAUSIERRORS FOR SBA_PLAUSIERRORS;
CREATE OR REPLACE PUBLIC SYNONYM SBA_FILTERS FOR SBA_FILTERS;
CREATE OR REPLACE PUBLIC SYNONYM SBA_PLAUSIS FOR SBA_PLAUSIS;
CREATE OR REPLACE PUBLIC SYNONYM SBA_EXPORTS FOR SBA_EXPORTS;
CREATE OR REPLACE PUBLIC SYNONYM SBA_PARAMETERS FOR SBA_PARAMETERS;
CREATE OR REPLACE PUBLIC SYNONYM SBASEQ FOR SBASEQ;


COMMIT;

