PROMPT 'Bitte für Wert 1 DATA_TABLESPACE angeben:'
DEFINE DATA_TABLESPACE 	= &1;

PROMPT 'Bitte für Wert 2 INDEX_TABLESPACE angeben:'
DEFINE INDEX_TABLESPACE = &2;

/****************************************************************************
 *	Stop in case of failure
 ****************************************************************************/
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

/****************************************************************************
 *	Create SDL Admin Tables
 ****************************************************************************/
CREATE TABLE SDL_FILTERS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	FILTERID		NUMBER,
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	REFOBJECT		NUMBER(2),
	SOURCE			VARCHAR(1020),
	AUTHORISATIONLEVEL	NUMBER(2),	
	ISACTIVE		NUMBER(1),
	ISDEFAULT		NUMBER(1),
	FILTERORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_FILTERS_PK PRIMARY KEY (FILTERID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);



CREATE TABLE SDL_PLAUSIS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	PLAUSIID		NUMBER,
	TYPE			NUMBER(2),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	SOURCE			VARCHAR(1020),
	OBJECTLEVEL		NUMBER(2),
	AUTHORISATIONLEVEL	NUMBER(2),
	ISACTIVE		NUMBER(1),
	ISCONFIRMABLE		NUMBER(1),
	ISCURRENTEXECUTIONONLY	NUMBER(1),
	VALIDFROM		NUMBER(4),
	VALIDTO			NUMBER(4),			
	PLAUSIORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_PLAUSIS_PK PRIMARY KEY (PLAUSIID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE TABLE SDL_EXPORTS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	EXPORTID		NUMBER,
	TYPE			NUMBER(2),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	SOURCE			VARCHAR(1020),
	AUTHORISATIONLEVEL	NUMBER(2),
	ISACTIVE		NUMBER(1),	
	EXPORTORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_EXPORTS_PK PRIMARY KEY (EXPORTID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

	
CREATE TABLE SDL_PARAMETERS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	PARAMETERID		NUMBER,
	FILTERID		NUMBER,
	PLAUSIID		NUMBER,
	EXPORTID		NUMBER,
	UNIQUENAME		VARCHAR(20),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DEFAULTVALUE		VARCHAR(60),
	PARAMETERORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_PARAMETERS_PK PRIMARY KEY (PARAMETERID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SDL_PARAMETERS_FILTER_FK FOREIGN KEY (FILTERID) 
		REFERENCES SDL_FILTERS(FILTERID)
		ON DELETE CASCADE,
	CONSTRAINT SDL_PARAMETERS_PLAUSI_FK FOREIGN KEY (PLAUSIID) 
		REFERENCES SDL_PLAUSIS(PLAUSIID)
		ON DELETE CASCADE,
	CONSTRAINT SDL_PARAMETERS_EXPORT_FK FOREIGN KEY (EXPORTID) 
		REFERENCES SDL_EXPORTS(EXPORTID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_PARAMETERS_FILTERS_ID ON SDL_PARAMETERS(FILTERID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_PARAMETERS_PLAUSIS_ID ON SDL_PARAMETERS(PLAUSIID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_PARAMETERS_EXPORTS_ID ON SDL_PARAMETERS(EXPORTID)
      TABLESPACE &INDEX_TABLESPACE;

/****************************************************************************
 *	Create SDL Init Tables
 ****************************************************************************/

CREATE TABLE SDL_CANTONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	CANTONID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	PLAUSI_USER		VARCHAR(50),
	PLAUSI_DATE		DATE,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	FINALISATION_USER	VARCHAR(50),
	FINALISATION_DATE	DATE,
	PLAUSIREPORT_DE		BLOB,
	PLAUSIREPORT_FR		BLOB,
	PLAUSIREPORT_IT		BLOB,
	USERTEXT		VARCHAR(252),		
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_CANTONS_PK PRIMARY KEY (CANTONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE TABLE SDL_CONFIGDELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	DELIVERYID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	ISDEFAULT		NUMBER(1),
	DL_USERS		VARCHAR(500),
	RO_USERS		VARCHAR(500),
	REFERENCEDATE		DATE,
	DUEDATE			DATE,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	USERTEXT		VARCHAR(252),		
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_CONFIGDELIVERIES_PK PRIMARY KEY (DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_CONFIGDELIVERIES_ID ON SDL_CONFIGDELIVERIES(CANTON, VERSION, DELIVERYCODE)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_CFGDEL_DELIVERYCODE ON SDL_CONFIGDELIVERIES(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;


CREATE TABLE SDL_SCHOOLS_CONFIGDELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	SCHOOLID		NUMBER,
	DELIVERYID		NUMBER,
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_SCHOOLS_CONFIGDELIVERY_PK PRIMARY KEY (SCHOOLID, DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SDL_SC_SCHOOLS_FK FOREIGN KEY (SCHOOLID) 
		REFERENCES SCHOOLS(SCHOOLID)
		ON DELETE CASCADE,
	CONSTRAINT SDL_SC_CONFIGDELIVERIES_FK FOREIGN KEY (DELIVERYID)
  		REFERENCES SDL_CONFIGDELIVERIES(DELIVERYID)
 		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_SCHOOLS_CF_SCHOOLID ON SDL_SCHOOLS_CONFIGDELIVERIES(SCHOOLID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_SCHOOLS_CF_DELIVERYID ON SDL_SCHOOLS_CONFIGDELIVERIES(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

/****************************************************************************
 *	Create SDL DATA Tables
 ****************************************************************************/

CREATE TABLE SDL_DELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	DELIVERYID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	DELIVERYDATE		DATE,
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(252),
	ISLOCKED		NUMBER(1),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_DELIVERIES_PK PRIMARY KEY (DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_DELIVERIES_ID ON SDL_DELIVERIES(CANTON, VERSION, DELIVERYCODE)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_DELIVERIES_CFGDELCODE ON SDL_DELIVERIES(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;


CREATE TABLE SDL_INTERVENTIONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	INTERVENTIONID		NUMBER,
	DELIVERYID		NUMBER,
	TYPE			NUMBER,
	INTERVENTION_USER	VARCHAR(50),
	INTERVENTION_DATE 	DATE,
	PLAUSIREPORT_DE		BLOB,
	PLAUSIREPORT_FR		BLOB,
	PLAUSIREPORT_IT		BLOB,
	DELIVERYFILE		BLOB,
	REPORT_DE		VARCHAR(1000),
	REPORT_FR		VARCHAR(1000),
	REPORT_IT		VARCHAR(1000),
	TEXT			VARCHAR(1000),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_INTERVENTIONS_PK PRIMARY KEY (INTERVENTIONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SDL_INTERVENTION_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SDL_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_INT_DEL_ID ON SDL_INTERVENTIONS(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE TABLE SDL_SCHOOLS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	SCHOOLID		NUMBER,
	DELIVERYID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	IDTYPE			VARCHAR(20),
	ID			VARCHAR(20),
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(256),
	ISTODELETE		NUMBER(1),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_SCHOOLS_PK PRIMARY KEY (SCHOOLID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SDL_SCHOOLS_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SDL_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_SCHOOLS_DELIVERIES_ID ON SDL_SCHOOLS(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE INDEX SDL_SCHOOLS_CANTON ON SDL_SCHOOLS(CANTON)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_SCHOOLS_VERSION ON SDL_SCHOOLS(VERSION)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_SCHOOLS_DELIVERYCODE ON SDL_SCHOOLS(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_SCHOOLS_CFGDELCODE ON SDL_SCHOOLS(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;


CREATE TABLE SDL_CLASSES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	CLASSID			NUMBER,
	SCHOOLID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	ID			VARCHAR(20),
	SCHOOLTYPE		NUMBER,
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(256),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_CLASSES_PK PRIMARY KEY (CLASSID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SDL_CLASSES_SCHOOL_FK FOREIGN KEY (SCHOOLID) 
		REFERENCES SDL_SCHOOLS(SCHOOLID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_CLASSES_SCHOOLS_ID ON SDL_CLASSES(SCHOOLID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE INDEX SDL_CLASSES_CANTON ON SDL_CLASSES(CANTON)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_CLASSES_VERSION ON SDL_CLASSES(VERSION)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_CLASSES_DELIVERYCODE ON SDL_CLASSES(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_CLASSES_CFGDELCODE ON SDL_CLASSES(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;


CREATE TABLE SDL_LEARNERS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	LEARNERID		NUMBER,
	CLASSID			NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	IDTYPE			VARCHAR(20),
	ID			VARCHAR(20),
	SEX			NUMBER(1),
	BIRTHDATE		DATE,
	NATIONALITY		NUMBER(4),
	LANGUAGE		NUMBER(3),
	RESIDENCE		NUMBER(4),
	HISTORIC_RESIDENCE	NUMBER(5),
	COUNTRY			NUMBER(4),
	SCHOOLTYPE		NUMBER,
	CANTONALYEAR		NUMBER(2),
	EDUCATIONTYPE		NUMBER(2),
	PLANSTATUS		NUMBER(2),
	PROFMATURA		NUMBER(1),
	PREV_SCHOOLTYPE		NUMBER,
	PREV_CANTONALYEAR	NUMBER(2),
	ADDITION1		VARCHAR(1024),
	ADDITION2		VARCHAR(1024),
	ADDITION3		VARCHAR(1024),
	ADDITION4		VARCHAR(1024),
	ADDITION5		VARCHAR(1024),
	ORIGDELIVERYDATA	VARCHAR(4000),
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(256),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_LEARNERS_PK PRIMARY KEY (LEARNERID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SDL_LEARNERS_CLASS_FK FOREIGN KEY (CLASSID) 
		REFERENCES SDL_CLASSES(CLASSID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_LEARNERS_CLASSES_ID ON SDL_LEARNERS(CLASSID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE INDEX SDL_LEARNERS_CANTON ON SDL_LEARNERS(CANTON)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_LEARNERS_VERSION ON SDL_LEARNERS(VERSION)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_LEARNERS_DELIVERYCODE ON SDL_LEARNERS(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_LEARNERS_CFGDELCODE ON SDL_LEARNERS(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_LEARNERS_PLAUSISTATUS ON SDL_LEARNERS(PLAUSISTATUS)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_LEARNERS_ID ON SDL_LEARNERS(ID)
	TABLESPACE MEB_INDEX;

CREATE TABLE SDL_PLAUSIERRORS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	ERRORID			NUMBER,
	CANTONID		NUMBER,
	DELIVERYID		NUMBER,
	SCHOOLID		NUMBER,
	CLASSID			NUMBER,
	LEARNERID		NUMBER,
	PLAUSIID		NUMBER,
	ERRORMSG_DE		VARCHAR(500),
	ERRORMSG_FR		VARCHAR(500),
	ERRORMSG_IT		VARCHAR(500),
	REPORTDATA		VARCHAR(1000),
	ISCONFIRMED		NUMBER(1),
	CONFIRMID		VARCHAR(50),
	ISTODELETE		NUMBER(1),
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,	
	USERTEXT		VARCHAR(252),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SDL_PLAUSIERRORS_PK PRIMARY KEY (ERRORID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SDL_PLAUSIERRORS_CANTON_FK FOREIGN KEY (CANTONID) 
		REFERENCES SDL_CANTONS(CANTONID)
		ON DELETE CASCADE,
	CONSTRAINT SDL_PLAUSIERRORS_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SDL_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE,
	CONSTRAINT SDL_PLAUSIERRORS_SCHOOL_FK FOREIGN KEY (SCHOOLID) 
		REFERENCES SDL_SCHOOLS(SCHOOLID)
		ON DELETE CASCADE,
	CONSTRAINT SDL_PLAUSIERRORS_CLASS_FK FOREIGN KEY (CLASSID) 
		REFERENCES SDL_CLASSES(CLASSID)
		ON DELETE CASCADE,
	CONSTRAINT SDL_PLAUSIERRORS_LEARNER_FK FOREIGN KEY (LEARNERID) 
		REFERENCES SDL_LEARNERS(LEARNERID)
		ON DELETE CASCADE,
	CONSTRAINT SDL_PLAUSIERRORS_PLAUSI_FK FOREIGN KEY (PLAUSIID) 
		REFERENCES SDL_PLAUSIS(PLAUSIID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SDL_PLAUSIERROR_DELIVERY on SDL_PLAUSIERRORS(DELIVERYID)
  tablespace &INDEX_TABLESPACE
  pctfree  20
  initrans 2
  maxtrans 255;

CREATE INDEX SDL_PLAUSIERRORS_CANTONS_ID ON SDL_PLAUSIERRORS(CANTONID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_PLAUSIERRORS_SCHOOLS_ID ON SDL_PLAUSIERRORS(SCHOOLID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_PLAUSIERRORS_CLASSES_ID ON SDL_PLAUSIERRORS(CLASSID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_PLAUSIERRORS_LEARNERS_ID ON SDL_PLAUSIERRORS(LEARNERID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_PLAUSIERRORS_PLAUSIS_ID ON SDL_PLAUSIERRORS(PLAUSIID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SDL_PLAUSIERRORS_DELIV_SCHOOL ON SDL_PLAUSIERRORS(DELIVERYID, SCHOOLID)
      TABLESPACE &INDEX_TABLESPACE;


/****************************************************************************
 *	Create SDL Sequence
 ****************************************************************************/
CREATE SEQUENCE SDLSEQ;

/****************************************************************************
 *	Create Synonyms
 ****************************************************************************/
CREATE OR REPLACE PUBLIC SYNONYM SDL_CANTONS FOR SDL_CANTONS;
CREATE OR REPLACE PUBLIC SYNONYM SDL_CONFIGDELIVERIES FOR SDL_CONFIGDELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SDL_SCHOOLS_CONFIGDELIVERIES FOR SDL_SCHOOLS_CONFIGDELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SDL_DELIVERIES FOR SDL_DELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SDL_INTERVENTIONS FOR SDL_INTERVENTIONS;
CREATE OR REPLACE PUBLIC SYNONYM SDL_SCHOOLS FOR SDL_SCHOOLS;
CREATE OR REPLACE PUBLIC SYNONYM SDL_CLASSES FOR SDL_CLASSES;
CREATE OR REPLACE PUBLIC SYNONYM SDL_LEARNERS FOR SDL_LEARNERS;
CREATE OR REPLACE PUBLIC SYNONYM SDL_PLAUSIERRORS FOR SDL_PLAUSIERRORS;
CREATE OR REPLACE PUBLIC SYNONYM SDL_FILTERS FOR SDL_FILTERS;
CREATE OR REPLACE PUBLIC SYNONYM SDL_PLAUSIS FOR SDL_PLAUSIS;
CREATE OR REPLACE PUBLIC SYNONYM SDL_EXPORTS FOR SDL_EXPORTS;
CREATE OR REPLACE PUBLIC SYNONYM SDL_PARAMETERS FOR SDL_PARAMETERS;
CREATE OR REPLACE PUBLIC SYNONYM SDLSEQ FOR SDLSEQ;


COMMIT;

