PROMPT 'Bitte für Wert 1 DATA_TABLESPACE angeben:'
DEFINE DATA_TABLESPACE 	= &1;

PROMPT 'Bitte für Wert 2 INDEX_TABLESPACE angeben:'
DEFINE INDEX_TABLESPACE = &2;

/****************************************************************************
 *	Stop in case of failure
 ****************************************************************************/
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

/****************************************************************************
 *	Create SSP Admin Tables
 ****************************************************************************/
CREATE TABLE SSP_FILTERS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	FILTERID		NUMBER,
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	REFOBJECT		NUMBER(2),
	SOURCE			VARCHAR(1020),
	AUTHORISATIONLEVEL	NUMBER(2),	
	ISACTIVE		NUMBER(1),
	ISDEFAULT		NUMBER(1),
	FILTERORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_FILTERS_PK PRIMARY KEY (FILTERID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);


CREATE TABLE SSP_PLAUSIS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	PLAUSIID		NUMBER,
	TYPE			NUMBER(2),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	SOURCE			VARCHAR(1020),
	OBJECTLEVEL		NUMBER(2),
	AUTHORISATIONLEVEL	NUMBER(2),
	ISACTIVE		NUMBER(1),
	ISCONFIRMABLE		NUMBER(1),
	ISCURRENTEXECUTIONONLY	NUMBER(1),
	VALIDFROM		NUMBER(4),
	VALIDTO			NUMBER(4),			
	PLAUSIORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_PLAUSIS_PK PRIMARY KEY (PLAUSIID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE TABLE SSP_EXPORTS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	EXPORTID		NUMBER,
	TYPE			NUMBER(2),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DESCRIPTION_DE		VARCHAR(252),
	DESCRIPTION_FR		VARCHAR(252),
	DESCRIPTION_IT		VARCHAR(252),
	SOURCE			VARCHAR(1020),
	AUTHORISATIONLEVEL	NUMBER(2),
	ISACTIVE		NUMBER(1),	
	EXPORTORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_EXPORTS_PK PRIMARY KEY (EXPORTID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

	
CREATE TABLE SSP_PARAMETERS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	PARAMETERID		NUMBER,
	FILTERID		NUMBER,
	PLAUSIID		NUMBER,
	EXPORTID		NUMBER,
	UNIQUENAME		VARCHAR(20),
	NAME_DE			VARCHAR(60),
	NAME_FR			VARCHAR(60),
	NAME_IT			VARCHAR(60),
	DEFAULTVALUE		VARCHAR(60),
	PARAMETERORDER		NUMBER(2),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_PARAMETERS_PK PRIMARY KEY (PARAMETERID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SSP_PARAMETERS_FILTER_FK FOREIGN KEY (FILTERID) 
		REFERENCES SSP_FILTERS(FILTERID)
		ON DELETE CASCADE,
	CONSTRAINT SSP_PARAMETERS_PLAUSI_FK FOREIGN KEY (PLAUSIID) 
		REFERENCES SSP_PLAUSIS(PLAUSIID)
		ON DELETE CASCADE,
	CONSTRAINT SSP_PARAMETERS_EXPORT_FK FOREIGN KEY (EXPORTID) 
		REFERENCES SSP_EXPORTS(EXPORTID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_PARAMETERS_FILTERS_ID ON SSP_PARAMETERS(FILTERID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PARAMETERS_PLAUSIS_ID ON SSP_PARAMETERS(PLAUSIID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PARAMETERS_EXPORTS_ID ON SSP_PARAMETERS(EXPORTID)
      TABLESPACE &INDEX_TABLESPACE;

/****************************************************************************
 *	Create SSP Init Tables
 ****************************************************************************/

CREATE TABLE SSP_CANTONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	CANTONID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	PLAUSI_USER		VARCHAR(50),
	PLAUSI_DATE		DATE,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	FINALISATION_USER	VARCHAR(50),
	FINALISATION_DATE	DATE,
	PLAUSIREPORT_DE		BLOB,
	PLAUSIREPORT_FR		BLOB,
	PLAUSIREPORT_IT		BLOB,
	USERTEXT		VARCHAR(252),		
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_CANTONS_PK PRIMARY KEY (CANTONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE TABLE SSP_CONFIGDELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	DELIVERYID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	ISDEFAULT		NUMBER(1),
	DL_USERS		VARCHAR(500),
	RO_USERS		VARCHAR(500),
	REFERENCEDATE		DATE,
	DUEDATE			DATE,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	USERTEXT		VARCHAR(252),		
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_CONFIGDELIVERIES_PK PRIMARY KEY (DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_CONFIGDELIVERIES_ID ON SSP_CONFIGDELIVERIES(CANTON, VERSION, DELIVERYCODE)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_CFGDEL_DELIVERYCODE ON SSP_CONFIGDELIVERIES(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;

CREATE TABLE SSP_SCHOOLS_CONFIGDELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	SCHOOLID		NUMBER,
	DELIVERYID		NUMBER,
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_SCHOOLS_CONFIGDELIVERY_PK PRIMARY KEY (SCHOOLID, DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SSP_SC_SCHOOLS_FK FOREIGN KEY (SCHOOLID) 
		REFERENCES SCHOOLS(SCHOOLID)
		ON DELETE CASCADE,
	CONSTRAINT SSP_SC_CONFIGDELIVERIES_FK FOREIGN KEY (DELIVERYID)
  		REFERENCES SSP_CONFIGDELIVERIES(DELIVERYID)
 		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_SCHOOLS_CF_SCHOOLID ON SSP_SCHOOLS_CONFIGDELIVERIES(SCHOOLID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_SCHOOLS_CF_DELIVERYID ON SSP_SCHOOLS_CONFIGDELIVERIES(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

/****************************************************************************
 *	Create SSP DATA Tables
 ****************************************************************************/

CREATE TABLE SSP_DELIVERIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	DELIVERYID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	DELIVERYDATE		DATE,
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(252),
	ISLOCKED		NUMBER(1),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_DELIVERIES_PK PRIMARY KEY (DELIVERYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_DELIVERIES_ID ON SSP_DELIVERIES(CANTON, VERSION, DELIVERYCODE)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_DELIVERIES_CFGDELCODE ON SSP_DELIVERIES(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;

CREATE TABLE SSP_INTERVENTIONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	INTERVENTIONID		NUMBER,
	DELIVERYID		NUMBER,
	TYPE			NUMBER,
	INTERVENTION_USER	VARCHAR(50),
	INTERVENTION_DATE 	DATE,
	PLAUSIREPORT_DE		BLOB,
	PLAUSIREPORT_FR		BLOB,
	PLAUSIREPORT_IT		BLOB,
	DELIVERYFILE		BLOB,
	REPORT_DE		VARCHAR(1000),
	REPORT_FR		VARCHAR(1000),
	REPORT_IT		VARCHAR(1000),
	TEXT			VARCHAR(1000),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_INTERVENTIONS_PK PRIMARY KEY (INTERVENTIONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SSP_INTERVENTION_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SSP_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_INT_DEL_ID ON SSP_INTERVENTIONS(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE TABLE SSP_PERSONS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	PERSONID		NUMBER,
	DELIVERYID		NUMBER,
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	IDTYPE			VARCHAR(20),
	ID			VARCHAR(20),
	SEX			NUMBER(1),
	BIRTHDATE		DATE,
	NATIONALITY		NUMBER(4),
	YEARSOFSERVICE		NUMBER(2),
	ORIGDELIVERYDATA	VARCHAR(4000),
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(256),
	ISTODELETE		NUMBER(1),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_PERSONS_PK PRIMARY KEY (PERSONID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SSP_PERSONS_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SSP_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_PERSONS_DELIVERIES_ID ON SSP_PERSONS(DELIVERYID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE INDEX SSP_PERSONS_CANTON ON SSP_PERSONS(CANTON)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PERSONS_VERSION ON SSP_PERSONS(VERSION)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PERSONS_DELIVERYCODE ON SSP_PERSONS(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PERSONS_CFGDELCODE ON SSP_PERSONS(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PERSONS_PLAUSISTATUS ON SSP_PERSONS(PLAUSISTATUS)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PERSONS_ID ON SSP_PERSONS(ID)
      TABLESPACE &INDEX_TABLESPACE;


CREATE TABLE SSP_ACTIVITIES (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	ACTIVITYID		NUMBER,
	PERSONID		NUMBER,
	CANTON			NUMBER(2),
	VERSION			NUMBER(4),
	DELIVERYCODE		VARCHAR(20),
	CONFIGDELIVERYCODE	VARCHAR(20),
	ID			NUMBER(2),
	SCHOOLIDTYPE		VARCHAR(20),
	SCHOOLID		VARCHAR(20),
	PERSCATEGORY		NUMBER,
	CONTRACTTYPE		NUMBER,
	QUALIFICATION		NUMBER,
	PENSUM			NUMBER(6,2),
	FULLTIMEREF		NUMBER(6,2),
	SCHOOLTYPE		NUMBER,
	DELIVERYSTATUS		NUMBER,
	PLAUSISTATUS		NUMBER,
	CREATION_USER		VARCHAR(50),
	CREATION_DATE		DATE,
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,
	PREVALIDATION_USER	VARCHAR(50),
	PREVALIDATION_DATE	DATE,
	VALIDATION_USER		VARCHAR(50),
	VALIDATION_DATE		DATE,
	USERTEXT		VARCHAR(256),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_ACTIVITIES_PK PRIMARY KEY (ACTIVITYID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SSP_ACTIVITIES_PERSON_FK FOREIGN KEY (PERSONID) 
		REFERENCES SSP_PERSONS(PERSONID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_ACTIVITIES_PERSONS_ID ON SSP_ACTIVITIES(PERSONID)
      TABLESPACE &INDEX_TABLESPACE;

CREATE INDEX SSP_ACTIVITIES_CANTON ON SSP_ACTIVITIES(CANTON)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_ACTIVITIES_VERSION ON SSP_ACTIVITIES(VERSION)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_ACTIVITIES_DELIVERYCODE ON SSP_ACTIVITIES(DELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_ACTIVITIES_CFGDELCODE ON SSP_ACTIVITIES(CONFIGDELIVERYCODE)
	TABLESPACE &INDEX_TABLESPACE;


CREATE TABLE SSP_PLAUSIERRORS (
     	-------------------------------------------------------------------------
	-- Attributes
	-------------------------------------------------------------------------
	ERRORID			NUMBER,
	CANTONID		NUMBER,
	DELIVERYID		NUMBER,
	PERSONID		NUMBER,
	ACTIVITYID		NUMBER,
	PLAUSIID		NUMBER,
	ERRORMSG_DE		VARCHAR(500),
	ERRORMSG_FR		VARCHAR(500),
	ERRORMSG_IT		VARCHAR(500),
	REPORTDATA		VARCHAR(1000),
	ISCONFIRMED		NUMBER(1),
	CONFIRMID		VARCHAR(50),
	ISTODELETE		NUMBER(1),
	MODIFICATION_USER	VARCHAR(50),
	MODIFICATION_DATE	DATE,	
	USERTEXT		VARCHAR(252),
	-------------------------------------------------------------------------
	-- Constraints
	-------------------------------------------------------------------------
  	CONSTRAINT SSP_PLAUSIERRORS_PK PRIMARY KEY (ERRORID)
		USING INDEX
			PCTFREE    20
			INITRANS   2
			MAXTRANS   255
			TABLESPACE &INDEX_TABLESPACE,
	CONSTRAINT SSP_PLAUSIERRORS_CANTON_FK FOREIGN KEY (CANTONID) 
		REFERENCES SSP_CANTONS(CANTONID)
		ON DELETE CASCADE,
	CONSTRAINT SSP_PLAUSIERRORS_DELIVERY_FK FOREIGN KEY (DELIVERYID) 
		REFERENCES SSP_DELIVERIES(DELIVERYID)
		ON DELETE CASCADE,
	CONSTRAINT SSP_PLAUSIERRORS_PERSON_FK FOREIGN KEY (PERSONID) 
		REFERENCES SSP_PERSONS(PERSONID)
		ON DELETE CASCADE,
	CONSTRAINT SSP_PLAUSIERRORS_ACTIVITY_FK FOREIGN KEY (ACTIVITYID) 
		REFERENCES SSP_ACTIVITIES(ACTIVITYID)
		ON DELETE CASCADE,
	CONSTRAINT SSP_PLAUSIERRORS_PLAUSI_FK FOREIGN KEY (PLAUSIID) 
		REFERENCES SSP_PLAUSIS(PLAUSIID)
		ON DELETE CASCADE
)
	TABLESPACE &DATA_TABLESPACE
	STORAGE	(INITIAL 1M NEXT 1M);

CREATE INDEX SSP_PLAUSIERROR_DELIVERY on SSP_PLAUSIERRORS(DELIVERYID)
  tablespace &INDEX_TABLESPACE
  pctfree  20
  initrans 2
  maxtrans 255;

CREATE INDEX SSP_PLAUSIERRORS_CANTONS_ID ON SSP_PLAUSIERRORS(CANTONID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PLAUSIERRORS_PERSONS_ID ON SSP_PLAUSIERRORS(PERSONID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PLAUSIERRORS_ACTIVITIES_ID ON SSP_PLAUSIERRORS(ACTIVITYID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PLAUSIERRORS_PLAUSIS_ID ON SSP_PLAUSIERRORS(PLAUSIID)
      TABLESPACE &INDEX_TABLESPACE;
CREATE INDEX SSP_PLAUSIERRORS_DELIV_PERSON ON SSP_PLAUSIERRORS(DELIVERYID, PERSONID)
      TABLESPACE &INDEX_TABLESPACE;


/****************************************************************************
 *	Create SSP Sequence
 ****************************************************************************/
CREATE SEQUENCE SSPSEQ;

/****************************************************************************
 *	Create Synonyms
 ****************************************************************************/
CREATE OR REPLACE PUBLIC SYNONYM SSP_CANTONS FOR SSP_CANTONS;
CREATE OR REPLACE PUBLIC SYNONYM SSP_CONFIGDELIVERIES FOR SSP_CONFIGDELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SSP_SCHOOLS_CONFIGDELIVERIES FOR SSP_SCHOOLS_CONFIGDELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SSP_DELIVERIES FOR SSP_DELIVERIES;
CREATE OR REPLACE PUBLIC SYNONYM SSP_INTERVENTIONS FOR SSP_INTERVENTIONS;
CREATE OR REPLACE PUBLIC SYNONYM SSP_PERSONS FOR SSP_PERSONS;
CREATE OR REPLACE PUBLIC SYNONYM SSP_ACTIVITIES FOR SSP_ACTIVITIES;
CREATE OR REPLACE PUBLIC SYNONYM SSP_PLAUSIERRORS FOR SSP_PLAUSIERRORS;
CREATE OR REPLACE PUBLIC SYNONYM SSP_FILTERS FOR SSP_FILTERS;
CREATE OR REPLACE PUBLIC SYNONYM SSP_PLAUSIS FOR SSP_PLAUSIS;
CREATE OR REPLACE PUBLIC SYNONYM SSP_EXPORTS FOR SSP_EXPORTS;
CREATE OR REPLACE PUBLIC SYNONYM SSP_PARAMETERS FOR SSP_PARAMETERS;
CREATE OR REPLACE PUBLIC SYNONYM SSPSEQ FOR SSPSEQ;


COMMIT;

