/**
 * MEB Evolutions 75, 76, 77, 78 : Augmenter la taille des champs
 */
ALTER TABLE CODEGROUPS
    MODIFY (CODETEXT VARCHAR(200), CODETEXTABBR	VARCHAR(200));

ALTER TABLE SDL_PLAUSIERRORS
    MODIFY (ERRORMSG_DE VARCHAR(800),ERRORMSG_FR VARCHAR(800), ERRORMSG_IT VARCHAR(800));

ALTER TABLE SBA_PLAUSIERRORS
    MODIFY (ERRORMSG_DE VARCHAR(800),ERRORMSG_FR VARCHAR(800), ERRORMSG_IT VARCHAR(800));

ALTER TABLE SSP_PLAUSIERRORS
    MODIFY (ERRORMSG_DE VARCHAR(800),ERRORMSG_FR VARCHAR(800), ERRORMSG_IT VARCHAR(800));

ALTER TABLE PLAUSIERROR
    MODIFY (ERRORMSG_D VARCHAR(800),ERRORMSG_F VARCHAR(800));