application.title=BFS: Statistik des Schulpersonals

## Plausierrors
plausierror.WrongAhvNr=Plausi 1.4: Die AHV-Nummer ist nicht korrekt
plausierror.WrongYearsOfService=Plausi 2.1: Die Jahre im Schuldienst müssen zwischen 0 und {0} sein
plausierror.WrongAge=Plausi 2.2: Das Alter muss zwischen {0} und {1} sein
plausierror.PensumTooHigh=Plausi 2.3: Das angegebene Pensum ({0} Std pro Woche) ist höher als die Basis Vollzeit ({1} Std pro Woche). 
plausierror.PensumIsNull=Plausi 2.3: Das angegebene Pensum (0 Std pro Woche) ist nicht plausibel.
plausierror.NoPerson=Plausi 3.1: Keine Person zur Lieferung vorhanden
plausierror.NoActivity=Plausi 3.2: Keine Tätigkeit zur Person vorhanden
plausierror.DuplicatePerson=Plausi 3.4: Die durch {0} identifizierte Person ist in der Lieferung mehrfach vorhanden
plausierror.DuplicateActivity=Plausi 3.5: Die Tätigkeit {0} ist doppelt vorhanden
plausierror.SchoolTypeNotEmpty=Plausi 3.6: Für Schulleitungsaktivitäten darf keine Schulart gesetzt sein
plausierror.SchoolTypeEmpty=Plausi 3.6: Für Lehr- und sonderpädagogische Aktivitäten muss eine Schulart gesetzt sein
plausierror.PersonDifferentInCanton=Plausi 4.1: Die personellen Merkmale der durch {0} identifizierten Personen stimmen nicht überein
plausierror.PersonDifferentInPreviousYear=Plausi 4.1: Die personellen Merkmale stimmen nicht mit dem Vorjahr überein
plausierror.UnknownSchool=Plausi 5.1: Schule unbekannt. Bitte BUR-Nr überprüfen. Der Typ der Schulidentifikation muss CH.BUR sein.
plausierror.NotAuthorizedUser=Plausi 5.2: Datenlieferant nicht berechtigt

## Delivery: XML Tag Names
xml.tag.deliveryDate.name=Lieferdatum
## Person: XML Tag Names
xml.tag.personIdCategory.name=Personen-Id-Typ
xml.tag.personId.name=Personen-Id
xml.tag.sex.name=Geschlecht
xml.tag.dateOfBirth.name=Geburtsdatum
xml.tag.nationality.name=Staatsangehörigkeit
xml.tag.yearsInAct.name=Jahre im Schuldienst
xml.tag.com.name=Kommentar
## Activity: XML Tag Names
xml.tag.actNr.name=Tätigkeitsnummer
xml.tag.catPers.name=Personalkategorie
xml.tag.status.name=Art des Arbeitsvertrags
xml.tag.qualification.name=Qualifikation
xml.tag.instIdCategory.name=Schul-Id-Typ
xml.tag.instId.name=Schul-Id
xml.tag.volAct.name=Pensum
xml.tag.fulltimeRef.name=Basis Vollzeit
xml.tag.ctSchArt.name=Schulart

# init status export
user.status.not.found=Der Benutzer ist nicht in der Benutzerverwaltung IDM als SSP Benutzer registriert.