CREATE TABLE SBG_UPLOAD_FILE (
                                       ID NUMBER(38,0) NOT NULL,
                                       NAME VARCHAR2(4000) NOT NULL,
                                       FILETYPE VARCHAR2(4000) NOT NULL,
                                       CONTENT BLOB,
                                       INTERVENTIONID NUMBER(38,0) NOT NULL,
                                       CONSTRAINT SBG_UPLOAD_FILE_PK PRIMARY KEY (ID),
                                       CONSTRAINT FK_ACTIONID FOREIGN KEY (INTERVENTIONID) REFERENCES M_MEB.ACTION(ACTIONID) ON DELETE CASCADE
);

CREATE OR REPLACE PUBLIC SYNONYM SBG_UPLOAD_FILE FOR SBG_UPLOAD_FILE;

GRANT SELECT, UPDATE, INSERT, DELETE ON SBG_UPLOAD_FILE TO MEB_APPL_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON SBG_UPLOAD_FILE TO BFS_ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON SBG_UPLOAD_FILE TO U_USER;
GRANT SELECT, UPDATE, INSERT, DELETE ON SBG_UPLOAD_FILE TO BFS_ADMIN_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON SBG_UPLOAD_FILE TO SBG_APPL_ROL;