CREATE TABLE UPLOAD_FILE (
                                   ID NUMBER(38,0) NOT NULL,
                                   NAME VARCHAR2(4000) NOT NULL,
                                   FILETYPE VARCHAR2(4000) NOT NULL,
                                   CONTENT BLOB,
                                   INTERVENTIONID NUMBER(38,0) NOT NULL,
                                   CONSTRAINT UPLOAD_FILE_PK PRIMARY KEY (ID),
                                   CONSTRAINT FK_INTERVENTIONID FOREIGN KEY (INTERVENTIONID) REFERENCES M_MEB.SDL_CANTONINTERVENTIONS(INTERVENTIONID) ON DELETE CASCADE
);

CREATE OR REPLACE PUBLIC SYNONYM SDL_UPLOAD_FILE FOR SDL_UPLOAD_FILE;

GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_UPLOAD_FILE TO MEB_APPL_ROLE;
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_UPLOAD_FILE TO U_USER;
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_UPLOAD_FILE TO BFS_ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON SDL_UPLOAD_FILE TO BFS_ADMIN_ROLE;