BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CODEGROUPS MODIFY (CODETEXT VARCHAR2(200), CODETEXTABBR VARCHAR2(200))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SDL_PLAUSIERRORS MODIFY (ERRORMSG_FR VARCHAR2(800))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SBA_PLAUSIERRORS MODIFY (ERRORMSG_FR VARCHAR2(800))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SSP_PLAUSIERRORS MODIFY (ERRORMSG_FR VARCHAR2(800))';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
