BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE PERSON MODIFY USERCOMMENT VARCHAR2(1024 CHAR)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE EVENT MODIFY USERCOMMENT VARCHAR2(1024 CHAR)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
