-- Rename UPLOAD_FILE to SDL_UPLOAD_FILE if it exists
BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE UPLOAD_FILE RENAME TO SDL_UPLOAD_FILE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN  -- ORA-00942 = table does not exist
      RAISE;
END IF;
END;
/

-- Create synonym (safe)
BEGIN
EXECUTE IMMEDIATE 'CREATE OR REPLACE PUBLIC SYNONYM SDL_UPLOAD_FILE FOR SDL_UPLOAD_FILE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop legacy synonym if exists
BEGIN
EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM UPLOAD_FILE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
