-- SDL
INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SDL_CANTONINTTYPE',2125,'fr','Fichier téléchargé','Fichier téléchargé' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SDL_CANTONINTTYPE' AND CODE=2125 AND LANGUAGE='fr');

INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SDL_CANTONINTTYPE',2125,'de','Heruntergeladene Datei','Heruntergeladene Datei' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SDL_CANTONINTTYPE' AND CODE=2125 AND LANGUAGE='de');

INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SDL_CANTONINTTYPE',2125,'it','Heruntergeladene Datei','Heruntergeladene Datei' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SDL_CANTONINTTYPE' AND CODE=2125 AND LANGUAGE='it');


-- SBA
-- FR
INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SBA_CANTONINTTYPE',2125,'fr','Fichier téléchargé','Fichier téléchargé' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SBA_CANTONINTTYPE' AND CODE=2125 AND LANGUAGE='fr');

-- DE
INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SBA_CANTONINTTYPE',2125,'de','Heruntergeladene Datei','Heruntergeladene Datei' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SBA_CANTONINTTYPE' AND CODE=2125 AND LANGUAGE='de');

-- IT
INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SBA_CANTONINTTYPE',2125,'it','Heruntergeladene Datei','Heruntergeladene Datei' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SBA_CANTONINTTYPE' AND CODE=2125 AND LANGUAGE='it');



-- SBG
-- FR
INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SBG_ACTIONTYPE',13,'fr','Fichier téléchargé','Fichier téléchargé' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SBG_ACTIONTYPE' AND CODE=13 AND LANGUAGE='fr');

-- DE
INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SBG_ACTIONTYPE',13,'de','Heruntergeladene Datei','Heruntergeladene Datei' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SBG_ACTIONTYPE' AND CODE=13 AND LANGUAGE='de');

-- IT
INSERT INTO CODEGROUPS (ID,CODEGROUPID,CODE,LANGUAGE,CODETEXTABBR,CODETEXT)
SELECT MEBSEQ.NEXTVAL,'SBG_ACTIONTYPE',13,'it','Heruntergeladene Datei','Heruntergeladene Datei' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM CODEGROUPS WHERE CODEGROUPID='SBG_ACTIONTYPE' AND CODE=13 AND LANGUAGE='it');

