CREATE OR REPLACE FORCE VIEW "M_MEB"."V_SCHUL"
("LOCAL_ID", "ENT_UNIT_OID", "NAME1_TX", "MUNICIPALITY_CD", "CANTON_CD", "UNIT_STATUS_CD", "ACTIVITY_TYPE_CD", "NACE2008_CD", "NAME_TX", "ADMIN_FICTIV_FLG", "STAT_ACT_SDL_FLG", "STAT_ACT_SSP_FLG", "STAT_ACT_MATU_FLG", "STAT_ACT_SSP_FROM", "STAT_ACT_SSP_TO", "STAT_ACT_SDL_SSP_FROM", "STAT_ACT_SDL_SSP_TO", "STAT_ACT_MATU_FROM", "STAT_ACT_MATU_TO", "SDL_CANTONAL_ID", "SSP_CANTONAL_ID", "MATU_CANTONAL_ID", "INST_TYP_PRE_PRIM_FLG", "INST_TYP_PRIM_FLG", "INST_TYP_LOW_SEC_FLG", "INST_TYP_BLP_FLG", "INST_TYP_UP_SEC_MATU_FLG", "INST_TYP_UP_SEC_VOC_FLG", "INST_TYP_UP_SEC_FMS_FLG", "INST_TYP_POST_SEC_NO_TERT_FLG", "INST_TYP_UNI_FLG", "INST_TYP_HIGH_EDUC_FLG", "INST_TYP_HIGH_VOC_FLG", "LANG_GE_FLG", "LANG_FR_FLG", "LANG_IT_FLG", "LANG_RR_FLG", "LANG_EN_FLG", "LANG_OTHER_FLG", "CHAR_PUBL_FLG", "CHAR_PRIV_SUB_FLG", "CHAR_PRIV_NO_SUB_FLG", "DEF_LEVEL_INST_ADMIN_FLG", "DEF_LEVEL_INST_SITE_FLG", "CHIEF_LOCAL_ID", "ADMIN_NOGA_FLG", "LOCAL_LAST_UPDATE", "SCHUL_LAST_UPDATE", "NACE_LAST_UPDATE") AS
  SELECT
    "LOCAL_ID",
    "ENT_UNIT_OID",
    "NAME1_TX",
    "MUNICIPALITY_CD",
    "CANTON_CD",
    "UNIT_STATUS_CD",
    "ACTIVITY_TYPE_CD",
    "NACE2008_CD",
    "NAME_TX",
    "ADMIN_FICTIV_FLG",
    "STAT_ACT_SDL_FLG",
    "STAT_ACT_SSP_FLG",
    "STAT_ACT_MATU_FLG",
    "STAT_ACT_SSP_FROM",
    "STAT_ACT_SSP_TO",
    "STAT_ACT_SDL_SSP_FROM",
    "STAT_ACT_SDL_SSP_TO",
    "STAT_ACT_MATU_FROM",
    "STAT_ACT_MATU_TO",
    "SDL_CANTONAL_ID",
    "SSP_CANTONAL_ID",
    "MATU_CANTONAL_ID",
    "INST_TYP_PRE_PRIM_FLG",
    "INST_TYP_PRIM_FLG",
    "INST_TYP_LOW_SEC_FLG",
    "INST_TYP_BLP_FLG",
    "INST_TYP_UP_SEC_MATU_FLG",
    "INST_TYP_UP_SEC_VOC_FLG",
    "INST_TYP_UP_SEC_FMS_FLG",
    "INST_TYP_POST_SEC_NO_TERT_FLG",
    "INST_TYP_UNI_FLG",
    "INST_TYP_HIGH_EDUC_FLG",
    "INST_TYP_HIGH_VOC_FLG",
    "LANG_GE_FLG",
    "LANG_FR_FLG",
    "LANG_IT_FLG",
    "LANG_RR_FLG",
    "LANG_EN_FLG",
    "LANG_OTHER_FLG",
    "CHAR_PUBL_FLG",
    "CHAR_PRIV_SUB_FLG",
    "CHAR_PRIV_NO_SUB_FLG",
    "DEF_LEVEL_INST_ADMIN_FLG",
    "DEF_LEVEL_INST_SITE_FLG",
    "CHIEF_LOCAL_ID",
    "ADMIN_NOGA_FLG",
    "LOCAL_LAST_UPDATE",
    "SCHUL_LAST_UPDATE",
    "NACE_LAST_UPDATE"
  FROM BUR2000.V_SCHUL@TBU2.BFS.ADMIN.CH school
  WHERE (stat_act_sdl_flg = 1
         OR stat_act_ssp_flg = 1
         OR STAT_ACT_MATU_FLG = 1)
        AND ((SELECT
                COUNT(*)
              FROM BUR2000.V_SCHUL@TBU2.BFS.ADMIN.CH
              WHERE local_id = school.local_id
                    AND unit_status_cd IN (1, 4, 5)) = 1
             AND school.unit_status_cd IN (1, 4, 5));