# --------------------------------
# Hibernate properties
# --------------------------------
hibernate.show_sql=true
hibernate.format_sql=false
# --------------------------------
# JNDI Datasource
# --------------------------------
jndi.datasource=jdbc/meb
# --------------------------------
# Konfiguration properties
# --------------------------------
configuration.idmdomain=MEB
configuration.idmserverurl=https://services.gate-r.eiam.admin.ch/nevisidm/services/v1_45/AdminService
configuration.keyStore=
configuration.keyStorePassword=
configuration.idm.implementation=idmUserServiceMock
configuration.sashost=bernoulli.bfs.admin.ch
configuration.sasport=8242
configuration.sasuser=mebsasup
configuration.saspassword=sas7up2MEB
configuration.saspoolminsize=5
configuration.saspoolmaxsize=10
configuration.saspoolminavailable=4
configuration.saspoolservershutdownafter=3
configuration.mail.from=sbg-sfpi@bfs.admin.ch	