package ch.admin.bfs.sbg.psist;

import java.io.*;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.Date;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import java.util.zip.ZipOutputStream;

import ch.bfs.meb.server.commons.util.ValidationUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import ch.admin.bfs.sbg.transfer.Action;
import ch.admin.bfs.sbg.util.HibernateUtil;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 * Event generated by MyEclipse - Hibernate Tools
 */
public class PersistAction extends Action implements java.io.Serializable {

    private static final long serialVersionUID = -6513696869789555648L;

    private static final Log LOGGER = LogFactory.getLog(PersistAction.class);

    private Blob plausireportBlob_de;
    private Blob plausireportBlob_fr;
    private Blob deliveryfile;

    // Constructors

    /** default constructor */
    public PersistAction() {}

    /** full constructor */
    public PersistAction(Long deliveryid, Long type, String actionUserEmail, Date executiondate, String validationreport_de, String validationreport_fr) {
        setDeliveryid(deliveryid);
        setType(type);
        setActionuser(actionUserEmail);
        setExecutiondate(executiondate);
        setValidationreport_de(validationreport_de);
        setValidationreport_fr(validationreport_fr);
    }

    /** copy from transient action */
    public PersistAction(Action action) {
        setDeliveryid(action.getDeliveryid());
        setType(action.getType());
        setActionuser(action.getActionuser());
        setExecutiondate(action.getExecutiondate());
        setValidationreport_de(action.getValidationreport_de());
        setValidationreport_fr(action.getValidationreport_fr());
    }

    public byte[] getPlausireport_de() {
        return extractBytesFromBlob(plausireportBlob_de);
    }

    public Blob getPlausireportBlob_de() {
        return plausireportBlob_de;
    }

    public void setPlausireportBlob_de(Blob plausireport) {
        this.plausireportBlob_de = plausireport;
    }

    public byte[] getPlausireport_fr() {
        return extractBytesFromBlob(plausireportBlob_fr);
    }

    public Blob getPlausireportBlob_fr() {
        return plausireportBlob_fr;
    }

    public void setPlausireportBlob_fr(Blob plausireport) {
        this.plausireportBlob_fr = plausireport;
    }

    public Blob getDeliveryfile() {
        return this.deliveryfile;
    }

    public void setDeliveryfile(Blob deliveryfile) {
        this.deliveryfile = deliveryfile;
    }

    public byte[] getZippedDelivery() throws SQLException {
        return deliveryfile.getBytes(1L, (int) deliveryfile.length());
    }

    public String getDelivery() throws SQLException, IOException {
        ZipInputStream in = new ZipInputStream(new ByteArrayInputStream(deliveryfile.getBytes(1L, (int) deliveryfile.length())));
        // Get the first entry
        in.getNextEntry();

        InputStreamReader reader = new InputStreamReader(in);
        StringBuilder sbgFile = new StringBuilder();

        // Read data from the ZIP stream
        char[] buf = new char[1024];
        int len;
        while ((len = reader.read(buf)) > 0) {
            sbgFile.append(buf, 0, len);
        }

        return sbgFile.toString();
    }

    public void setDelivery(String file) throws IOException {
        boolean isXml = file.charAt(0) == '<';
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        ZipOutputStream zipOut = new ZipOutputStream(os);
        if (isXml) {
            zipOut.putNextEntry(new ZipEntry("Delivery.xml"));
        } else {
            zipOut.putNextEntry(new ZipEntry("Delivery.csv"));
        }
        byte[] bytes = file.getBytes();
        zipOut.write(bytes, 0, bytes.length);
        zipOut.closeEntry();
        zipOut.close();
        setDeliveryfile(HibernateUtil.createBlob(os.toByteArray()));
    }

    public void setDelivery(File file, String deliveryFileName) throws IOException {
        FileInputStream is = new FileInputStream(file);
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        ZipOutputStream zipOut = new ZipOutputStream(os);
        zipOut.putNextEntry(new ZipEntry(deliveryFileName));
        byte[] buf = new byte[1024];
        int len;
        while ((len = is.read(buf)) > 0) {
            zipOut.write(buf, 0, len);
        }
        zipOut.closeEntry();
        zipOut.close();
        is.close();
        setDeliveryfile(HibernateUtil.createBlob(os.toByteArray()));
    }


    public byte[] convertXlsToXlsx(InputStream xlsInputStream) throws IOException {
        try (HSSFWorkbook hssfWorkbook = new HSSFWorkbook(xlsInputStream);
             XSSFWorkbook xssfWorkbook = new XSSFWorkbook();
             ByteArrayOutputStream xlsxOutputStream = new ByteArrayOutputStream()) {

            // Copier chaque feuille du fichier XLS vers le fichier XLSX
            for (int i = 0; i < hssfWorkbook.getNumberOfSheets(); i++) {
                Sheet oldSheet = hssfWorkbook.getSheetAt(i);
                Sheet newSheet = xssfWorkbook.createSheet(oldSheet.getSheetName());
                copySheet(oldSheet, newSheet);
            }

            // Écrire le fichier XLSX en mémoire
            xssfWorkbook.write(xlsxOutputStream);
            return xlsxOutputStream.toByteArray();
        }
    }

    private void copySheet(Sheet oldSheet, Sheet newSheet) {
        for (int rowIndex = 0; rowIndex <= oldSheet.getLastRowNum(); rowIndex++) {
            Row oldRow = oldSheet.getRow(rowIndex);
            if (oldRow != null) {
                Row newRow = newSheet.createRow(rowIndex);
                copyRow(oldRow, newRow);
            }
        }
    }

    private void copyRow(Row oldRow, Row newRow) {
        for (int cellIndex = 0; cellIndex < oldRow.getLastCellNum(); cellIndex++) {
            Cell oldCell = oldRow.getCell(cellIndex);
            if (oldCell != null) {
                Cell newCell = newRow.createCell(cellIndex, oldCell.getCellType());
                copyCell(oldCell, newCell);
            }
        }
    }

    private void copyCell(Cell oldCell, Cell newCell) {
        CellType cellType = CellType.forInt(oldCell.getCellType()); // Pour Apache POI 4.x et supérieur

        switch (cellType) {
            case STRING:
                newCell.setCellValue(oldCell.getStringCellValue());
                break;
            case NUMERIC:
                newCell.setCellValue(oldCell.getNumericCellValue());
                break;
            case BOOLEAN:
                newCell.setCellValue(oldCell.getBooleanCellValue());
                break;
            case FORMULA:
                newCell.setCellFormula(oldCell.getCellFormula());
                break;
            case ERROR:
                newCell.setCellErrorValue(oldCell.getErrorCellValue());
                break;
            case BLANK:
            default:
                newCell.setCellValue("");
                break;
        }
    }
    /**
     * Méthode utilitaire pour extraire un byte[] depuis un BLOB avec conversion .xls -> .xlsx si nécessaire.
     */
    private byte[] extractBytesFromBlob(Blob blob) {
        try {
            if (blob != null) {
                byte[] fileData = blob.getBytes(1L, (int) blob.length());

                if (ValidationUtils.isXlsFormat(fileData)) {
                    return convertXlsToXlsx(new ByteArrayInputStream(fileData));
                }

                return fileData;
            }
        } catch (SQLException | IOException e) {
            throw new IllegalStateException("Unable to process blob file", e);
        }

        return null;
    }
    /**
     * Convertit un tableau de bytes en SerialBlob ou retourne null si null.
     */
    private javax.sql.rowset.serial.SerialBlob toSerialBlob(byte[] data) {
        if (data == null) return null;
        try {
            return new javax.sql.rowset.serial.SerialBlob(data);
        } catch (SQLException e) {
            throw new IllegalStateException("Error converting byte array to SerialBlobfile", e);
        }
    }
}
