//package ch.admin.bfs.sbg.psist;
//
//import ch.admin.bfs.sbg.transfer.Macro;
//import ch.admin.bfs.sbg.transfer.MacroParameterList;
//import ch.bfs.meb.sbg.server.integration.dto.SbgParameter;
//
//import java.util.SortedSet;
//import java.util.TreeSet;
//
//
///**
// * Event generated by MyEclipse - Hibernate Tools
// */
//public class PersistMacro extends Macro implements java.io.Serializable
//{
//
//	private static final long serialVersionUID = -6513696869789555648L;
//
//	private SortedSet<SbgParameter> macroParameters = new TreeSet<SbgParameter>();
//
//	// Constructors
//
//	/**
//	 * default constructor
//	 */
//	public PersistMacro()
//	{
//	}
//
//	/**
//	 * copy from transient macro
//	 */
//	public PersistMacro(Macro transMacro)
//	{
//		setMacroid(transMacro.getMacroid());
//		setType(transMacro.getType());
//		setObjecttype(transMacro.getObjecttype());
//		setName_de(transMacro.getName_de());
//		setName_fr(transMacro.getName_fr());
//		setDescription_de(transMacro.getDescription_de());
//		setDescription_fr(transMacro.getDescription_fr());
//		setSource(transMacro.getSource());
//		setOrder(transMacro.getOrder());
//		setAuthorisationlevel(transMacro.getAuthorisationlevel());
//		setIsactive(transMacro.getIsactive());
//		setIsconfirmable(transMacro.getIsconfirmable());
//		setModuser(transMacro.getModuser());
//		setModdate(transMacro.getModdate());
//		setParameters(transMacro.getParameters());
//	}
//
//
//	public SortedSet<SbgParameter> getMacroParameters()
//	{
//		return this.macroParameters;
//	}
//
//	public void setMacroParameters(SortedSet<SbgParameter> macroParameters)
//	{
//		this.macroParameters = macroParameters;
//	}
//
//	/* (non-Javadoc)
//	 * @see ch.admin.bfs.sbg.transfer.Macro#getParameters()
//	 */
//	@Override
//	public MacroParameterList getParameters()
//	{
//		// set ParameterList from PersistSet
//		super.setParameters(new MacroParameterList(macroParameters));
//
//		return super.getParameters();
//	}
//
//	/* (non-Javadoc)
//	 * @see ch.admin.bfs.sbg.transfer.Macro#setParameters(ch.admin.bfs.sbg.transfer.MacroParameterList)
//	 */
//	@Override
//	public void setParameters(MacroParameterList value)
//	{
//		// override the PersistSet
//		macroParameters.clear();
//		for(SbgParameter transferParameter : value.getMacroParameter())
//		{
//			macroParameters.add(transferParameter);
//		}
//
//		super.setParameters(value);
//	}
//}
