package ch.admin.bfs.sbg.psist;

import java.util.HashSet;
import java.util.Set;

import ch.admin.bfs.sbg.transfer.Person;
import ch.bfs.meb.sbg.server.integration.dto.SbgEvent;

/**
 * Person generated by MyEclipse - Hibernate Tools
 */
public class PersistPerson extends Person implements java.io.Serializable {

    private static final long serialVersionUID = -6513696769789515648L;

    private Set<SbgEvent> events = new HashSet<SbgEvent>();

    // Constructors

    /**
     * default constructor
     */
    public PersistPerson() {}

    /**
     * copy from transient person
     */
    public PersistPerson(Person transPers) {
        setPid(transPers.getPid());
        setDeliveryId(transPers.getDeliveryId());
        setCanton(transPers.getCanton());
        setVersion(transPers.getVersion());
        setIdType(transPers.getIdType());
        setId(transPers.getId());
        setSex(transPers.getSex());
        setBirthDate(transPers.getBirthDate());
        setNewBirthDate(transPers.getNewBirthDate());
        setUserComment(transPers.getUserComment());
        setDeliveryText(transPers.getDeliveryText());
        setModUser(transPers.getModUser());
        setModDate(transPers.getModDate());
        setValidationUser(transPers.getValidationUser());
        setValidationDate(transPers.getValidationDate());
        setIsToDelete(transPers.getIsToDelete());
        setPlausiStatus(transPers.getPlausiStatus());
        setStatus(transPers.getStatus());
        setPlausiErrors(transPers.getPlausiErrors());
    }

    public Set<SbgEvent> getEvents() {
        return this.events;
    }

    public void setEvents(Set<SbgEvent> events) {
        this.events = events;
    }

    protected static int compareLong(Long long1, Long long2) {
        Long l1 = long1 == null ? 0L : long1;
        Long l2 = long2 == null ? 0L : long2;
        return l1.compareTo(l2);
    }
}
