package ch.admin.bfs.sbg.psist;

import java.util.Date;

import ch.admin.bfs.sbg.transfer.SbgDelivery;

/**
 * Event generated by MyEclipse - Hibernate Tools
 */
public class PersistDelivery extends SbgDelivery implements java.io.Serializable {
    private static final long serialVersionUID = 3364292346864917246L;

    // Constructors

    /**
     * default constructor
     */
    public PersistDelivery() {}

    /**
     * full constructor
     */
    public PersistDelivery(Long canton, Long version, String deliveryUserEmail, Date deliverydate, Long plausistatus, Long status, Long islocked) {
        super(canton, version, deliveryUserEmail, deliverydate, plausistatus, status, islocked);
    }

    /**
     * copy from transient event
     */
    public PersistDelivery(SbgDelivery transDelivery) {
        setDeliveryid(transDelivery.getDeliveryid());
        setCanton(transDelivery.getCanton());
        setVersion(transDelivery.getVersion());
        setDeliveryuser(transDelivery.getDeliveryuser());
        setDeliverydate(transDelivery.getDeliverydate());
        setPlausistatus(transDelivery.getPlausistatus());
        setStatus(transDelivery.getStatus());
        setIslocked(transDelivery.getIslocked());
    }
}
