{{ $hasAzureDevopsRepo := eq (include "generic-application-pipeline.hasAzureDevopsRepo" .) "true" }}
{{ $hasBitbucketRepo := eq (include "generic-application-pipeline.hasBitbucketRepo" .) "true" }}

{{- if and (.Values.global).secrets (.Values.global).secrets.externalStore (.Values.global).secrets.externalStore.enabled (.Values.global).secrets.externalStore.paths }}
{{- if (.Values.global).secrets.externalStore.paths.bitbucket }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.bitbucket.name }}-es
  labels:
    {{- include "generic-application-pipeline.metadata.template-labels" . | nindent 4 }}
  annotations:
    {{- include "generic-application-pipeline.metadata.template-annotations" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cop-{{ required "global.secrets.externalStore.paths.bitbucket.vault is required" (.Values.global).secrets.externalStore.paths.bitbucket.vault }}
    kind: SecretStore

  refreshInterval: 5m0s

  target:
    name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.bitbucket.property }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      # for Tekton
      type: kubernetes.io/ssh-auth
      metadata:
        annotations:
          # to be recognized from Tekton, consider Bitbucket Campus and Azure too
          tekton.dev/git-0: bitbucket.bit.admin.ch
          tekton.dev/git-1: bitbucket-campus.bit.admin.ch
          tekton.dev/git-2: devops-server.admin.ch
      data:
        # for Tekton
        ssh-privatekey: '{{ `{{ .gitkey }}` }}'
        id_rsa: '{{ `{{ .gitkey }}` }}'
        known_hosts: |
          bitbucket.bit.admin.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfO3Gh1kORpv+Zoeggwas8Tfn93QBhXSchZP5Po7XpiATnf+e9E/goZ214UuWBSkHzqy5tico4Jkk9l1uDedDXR9wxfK1xzLUPYsiUjtThkwChaEFawyWetKjzqVOKrZknZuRxUkDdH1oK0yj7uqWd7VNA5zCsVjstVxK6XF5v3wQP17xtT24imrUeXIdcmRC3IecPnlJ0KzfXNc0KP72t6/+7nfsFCft7gVp1oS4xG7Cff7AbO0I13w9gLvXk5hfkRu2YkNG0305YghETo1s8xXGHJFx7gXBXXch2m5+OlirSGsJZXLojfX0fcVvbIZUzWy3S4XRU7y1OjhJlMTVV
          bitbucket-campus.bit.admin.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7T1hQiHkaTlR/8BWqonAET3hhuq9pSug0tdOape+K12NUGUACOJGvrJ5lSAqXF0VRK0G2G773SRtl1c80yl9fg8liILloUCxzL6Q/hOu10daq7OghnC0SRQUbEtY/D8eH7rfiYxpb31otFTvBR/W+Je5N4BcCuDpJEeRAv1Qog2xZ9MvoWsX8VcklzYuavI8ktJdzGq2DS+IsReMKFJx9Ji7jWG4e6HEgIg/cEQ+W8LsRXC4n1pUL6M8YXOKJiNcNtt59ebjiVJeWaAK3yTF21a0eoxyX1Wg+U4SPf4Ez+TFepO6qKH9ghAzRiDLWKWDAyDupNvgCxn9Hb6bJfk8d
          devops-server.admin.ch,10.222.11.225 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcj+ZAx4eg/S5LEENbcA1yNN7Yfd8cM1QZrxr+jV9pqZmp+ku6QJWVkQ4tcd4AM37cNLrMEoJR7bu3MvTW2zuLaoGeQs4ij2gskxmmw+1OKQDhuqei/oJTmBuKN7a56WdPVpZG1z0OV13CDu6A0d52Mao80aS2FHFInkNoLuuJ6lwHw5xFVgGUr1gvi05Hun0gEMp39bGtAZcMeAuBGagl6jwm2DzkspgfAm6Yan81nF7pcYXq6bHdLmot5yCQda3VJ5F8kBj5YkZlkZNtrKWULOPQMCSKKeHqFhI0ga4ccyfEw/Unc5smB7eqrNYhD9dK+6geaBaythTpvPzqOChT
  data:
    - secretKey: gitkey
      remoteRef:
        key: {{ required "global.secrets.externalStore.paths.bitbucket.id is required" (.Values.global).secrets.externalStore.paths.bitbucket.id }}
        property: {{ required "global.secrets.externalStore.paths.bitbucket.property is required" (.Values.global).secrets.externalStore.paths.bitbucket.property }}
{{ end }}

{{- if and (.Values.global).secrets.externalStore.paths.azure $hasAzureDevopsRepo }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.azure.name }}-es
  labels:
    {{- include "generic-application-pipeline.metadata.template-labels" . | nindent 4 }}
  annotations:
    {{- include "generic-application-pipeline.metadata.template-annotations" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cop-{{ required "global.secrets.externalStore.paths.azure.vault is required" (.Values.global).secrets.externalStore.paths.azure.vault }}
    kind: SecretStore

  refreshInterval: 5m0s

  target:
    name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.azure.property }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      # for Tekton
      type: kubernetes.io/ssh-auth
      metadata:
        annotations:
          # to be recognized from Tekton, consider Bitbucket Campus and Azure too
          tekton.dev/git-0: bitbucket.bit.admin.ch
          tekton.dev/git-1: bitbucket-campus.bit.admin.ch
          tekton.dev/git-2: devops-server.admin.ch
      data:
        # for Tekton
        ssh-privatekey: '{{ `{{ .gitkey }}` }}'
        id_rsa: '{{ `{{ .gitkey }}` }}'
        known_hosts: |
          bitbucket.bit.admin.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfO3Gh1kORpv+Zoeggwas8Tfn93QBhXSchZP5Po7XpiATnf+e9E/goZ214UuWBSkHzqy5tico4Jkk9l1uDedDXR9wxfK1xzLUPYsiUjtThkwChaEFawyWetKjzqVOKrZknZuRxUkDdH1oK0yj7uqWd7VNA5zCsVjstVxK6XF5v3wQP17xtT24imrUeXIdcmRC3IecPnlJ0KzfXNc0KP72t6/+7nfsFCft7gVp1oS4xG7Cff7AbO0I13w9gLvXk5hfkRu2YkNG0305YghETo1s8xXGHJFx7gXBXXch2m5+OlirSGsJZXLojfX0fcVvbIZUzWy3S4XRU7y1OjhJlMTVV
          bitbucket-campus.bit.admin.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7T1hQiHkaTlR/8BWqonAET3hhuq9pSug0tdOape+K12NUGUACOJGvrJ5lSAqXF0VRK0G2G773SRtl1c80yl9fg8liILloUCxzL6Q/hOu10daq7OghnC0SRQUbEtY/D8eH7rfiYxpb31otFTvBR/W+Je5N4BcCuDpJEeRAv1Qog2xZ9MvoWsX8VcklzYuavI8ktJdzGq2DS+IsReMKFJx9Ji7jWG4e6HEgIg/cEQ+W8LsRXC4n1pUL6M8YXOKJiNcNtt59ebjiVJeWaAK3yTF21a0eoxyX1Wg+U4SPf4Ez+TFepO6qKH9ghAzRiDLWKWDAyDupNvgCxn9Hb6bJfk8d
          devops-server.admin.ch,10.222.11.225 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcj+ZAx4eg/S5LEENbcA1yNN7Yfd8cM1QZrxr+jV9pqZmp+ku6QJWVkQ4tcd4AM37cNLrMEoJR7bu3MvTW2zuLaoGeQs4ij2gskxmmw+1OKQDhuqei/oJTmBuKN7a56WdPVpZG1z0OV13CDu6A0d52Mao80aS2FHFInkNoLuuJ6lwHw5xFVgGUr1gvi05Hun0gEMp39bGtAZcMeAuBGagl6jwm2DzkspgfAm6Yan81nF7pcYXq6bHdLmot5yCQda3VJ5F8kBj5YkZlkZNtrKWULOPQMCSKKeHqFhI0ga4ccyfEw/Unc5smB7eqrNYhD9dK+6geaBaythTpvPzqOChT
  data:
    - secretKey: gitkey
      remoteRef:
        key: {{ required "global.secrets.externalStore.paths.azure.id is required" (.Values.global).secrets.externalStore.paths.azure.id }}
        property: {{ required "global.secrets.externalStore.paths.azure.property is required" (.Values.global).secrets.externalStore.paths.azure.property }}
{{ end }}

{{- if (.Values.global).secrets.externalStore.paths.netrc }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.netrc.name }}-es
  labels:
    {{- include "generic-application-pipeline.metadata.template-labels" . | nindent 4 }}
  annotations:
    {{- include "generic-application-pipeline.metadata.template-annotations" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cop-{{ required "global.secrets.externalStore.paths.netrc.vault is required" (.Values.global).secrets.externalStore.paths.netrc.vault }}
    kind: SecretStore

  refreshInterval: 5m0s

  target:
    name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.netrc.property }}
    creationPolicy: Owner

  data:
    - secretKey: .netrc
      remoteRef:
        key: {{ required "global.secrets.externalStore.paths.netrc.id is required" (.Values.global).secrets.externalStore.paths.netrc.id }}
        property: {{ required "global.secrets.externalStore.paths.netrc.property is required" (.Values.global).secrets.externalStore.paths.netrc.property }}
{{ end }}

{{- if and (.Values.global).secrets.externalStore.paths.bitbucketAccessToken $hasBitbucketRepo }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.bitbucketAccessToken.name }}-es
  labels:
    {{- include "generic-application-pipeline.metadata.template-labels" . | nindent 4 }}
  annotations:
    {{- include "generic-application-pipeline.metadata.template-annotations" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cop-{{ required "global.secrets.externalStore.paths.bitbucketAccessToken.vault is required" (.Values.global).secrets.externalStore.paths.bitbucketAccessToken.vault }}
    kind: SecretStore

  refreshInterval: 5m0s

  target:
    name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.bitbucketAccessToken.property }}
    creationPolicy: Owner

  data:
    - secretKey: accesstoken
      remoteRef:
        key: {{ required "global.secrets.externalStore.paths.bitbucketAccessToken.id is required" (.Values.global).secrets.externalStore.paths.bitbucketAccessToken.id }}
        property: {{ required "global.secrets.externalStore.paths.bitbucketAccessToken.property is required" (.Values.global).secrets.externalStore.paths.bitbucketAccessToken.property }}
{{ end }}

{{- if and (.Values.global).secrets.externalStore.paths.azureDevopsAccessToken $hasAzureDevopsRepo }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.azureDevopsAccessToken.name }}-es
  labels:
    {{- include "generic-application-pipeline.metadata.template-labels" . | nindent 4 }}
  annotations:
    {{- include "generic-application-pipeline.metadata.template-annotations" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cop-{{ required "global.secrets.externalStore.paths.azureDevopsAccessToken.vault is required" (.Values.global).secrets.externalStore.paths.azureDevopsAccessToken.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 5m0s

  target:
    name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.azureDevopsAccessToken.property }}
    creationPolicy: Owner

  data:
    - secretKey: accesstoken
      remoteRef:
        key: {{ required "global.secrets.externalStore.paths.azureDevopsAccessToken.id is required" (.Values.global).secrets.externalStore.paths.azureDevopsAccessToken.id }}
        property: {{ required "global.secrets.externalStore.paths.azureDevopsAccessToken.property is required" (.Values.global).secrets.externalStore.paths.azureDevopsAccessToken.property }}
{{ end }}

{{- if (.Values.global).secrets.externalStore.paths.dependencyTrackApiKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.dependencyTrackApiKey.name }}-es
  labels:
    {{- include "generic-application-pipeline.metadata.template-labels" . | nindent 4 }}
  annotations:
    {{- include "generic-application-pipeline.metadata.template-annotations" . | nindent 4 }}
spec:
  secretStoreRef:
    name: cop-{{ required "global.secrets.externalStore.paths.dependencyTrackApiKey.vault is required" (.Values.global).secrets.externalStore.paths.dependencyTrackApiKey.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 5m0s

  target:
    name: {{ include "generic-application-pipeline.releaseName" . }}-{{ (.Values.global).secrets.externalStore.paths.dependencyTrackApiKey.property }}
    creationPolicy: Owner

  data:
    - secretKey: apiKey
      remoteRef:
        key: {{ required "global.secrets.externalStore.paths.dependencyTrackApiKey.id is required" (.Values.global).secrets.externalStore.paths.dependencyTrackApiKey.id }}
        property: {{ required "global.secrets.externalStore.paths.dependencyTrackApiKey.property is required" (.Values.global).secrets.externalStore.paths.dependencyTrackApiKey.property }}
{{ end }}

{{ end }}