# --------------------------------
# Konfiguration properties
# --------------------------------
configuration.idmdomain=MEB
configuration.idmserverurl=https://services.gate-r.eiam.admin.ch/nevisidm/services/v1_45/AdminService
configuration.keyStore=
configuration.keyStorePassword=
configuration.idm.implementation=idmUserServiceMock
configuration.commonserverurl=http://localhost:7001/mebserver
configuration.sdlweburl=http://localhost:7001/sdlweb
configuration.sspweburl=http://localhost:7001/sspweb
configuration.sbaweburl=http://localhost:7001/sbaweb
configuration.sbgweburl=http://localhost:7001/sbgweb