application.title=BFS: Statistik der Bildungsabschlüsse

## Plausierrors
plausierror.WrongAhvNr=Plausi 1.4: Die AHV-Nummer ist nicht korrekt
plausierror.WrongExamDate=Plausi 2.2: Das Prüfungsdatum muss im Referenzjahr liegen
plausierror.NoPerson=Plausi 3.2: Keine Person zur Lieferung vorhanden
plausierror.NoQualification=Plausi 3.3: Keine Qualifikation zur Person vorhanden
plausierror.DuplicatePerson=Plausi 3.4: Die durch {0} identifizierte Person ist in der Lieferung mehrfach vorhanden
plausierror.DuplicateQualification=Plausi 3.5: Die Qualifikation {0} ist doppelt vorhanden
plausierror.PersonDifferentInPreviousYear=Plausi 4.1: Die personellen Merkmale stimmen nicht mit dem Vorjahr überein
plausierror.PersonDifferentInPreviousYearInCanton=Plausi 4.1: Die personellen Merkmale der Person mit der Identifikation {0} stimmen nicht mit dem Vorjahr überein
plausierror.PersonDifferentInSdl=Plausi 4.2: Die personellen Merkmale stimmen nicht mit SdL überein
plausierror.UnknownSchool=Plausi 5.1: Schule unbekannt. Bitte BUR-Nr überprüfen. Der Typ der Schulidentifikation muss CH.BUR sein.
plausierror.NotAuthorizedUser=Plausi 3.1b): Datenlieferant nicht berechtigt

## Delivery: XML Tag Names
xml.tag.deliveryDate.name=Lieferdatum
## Person: XML Tag Names
xml.tag.personIdCategory.name=Personen-Id-Typ
xml.tag.personId.name=Personen-Id
xml.tag.sex.name=Geschlecht
xml.tag.dateOfBirth.name=Geburtsdatum
xml.tag.place.name=Wohnsitz (amtlicher Code)
xml.tag.placeHist.name=Wohnsitz (historisierter Code)
xml.tag.country.name=Wohnsitz (ausländisches Land)
xml.tag.com.name=Kommentar
## Qualification: XML Tag Names
xml.tag.instIdCategory.name=Schul-Id-Typ
xml.tag.instId.name=Schul-Id
xml.tag.bildArt.name=Bildungsart
xml.tag.extyp.name=Prüfungsart
xml.tag.examDate.name=Prüfungsdatum
xml.tag.exnr.name=Prüfungsnummer
xml.tag.res.name=Ergebnis
xml.tag.twolang.name=Zweisprachiger Abschluss

# init status export
user.status.not.found=Der Benutzer ist nicht in der Benutzerverwaltung IDM als SBA Benutzer registriert.