package ch.bfs.meb.sbg.server.integration.dto;

import java.io.Serializable;

import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

import ch.bfs.meb.server.commons.integration.dto.Parameter;
import lombok.Data;

/**
 * MacroParameter generated by MyEclipse - Hibernate Tools
 */
@Entity
@Data
@Table(name = "PARAMETER")
@AttributeOverrides({ @AttributeOverride(name = "name_de", column = @Column(name = "NAME_D")),
        @AttributeOverride(name = "name_fr", column = @Column(name = "NAME_F")), @AttributeOverride(name = "name_it", column = @Column(name = "NAME_I")) })
@GenericGenerator(name = "parameterseqgen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
        @org.hibernate.annotations.Parameter(name = "sequence_name", value = "SBGSEQ"),
        @org.hibernate.annotations.Parameter(name = "increment_size", value = "100"),
        @org.hibernate.annotations.Parameter(name = "optimizer", value = "pooled-lo") })
public class SbgParameter extends Parameter implements Serializable, Comparable {
    private static final long serialVersionUID = -6813646769389555648L;

    @Column
    private Long macroId;

    /**
     * Default constructor.
     */
    public SbgParameter() {}

    /**
     * Full constructor.
     */
    public SbgParameter(Long macroId, Long filterId, String uniqueName, String name_de, String name_fr, String defaultvalue) {
        setMacroId(macroId);
        setFilterId(filterId);
        setUniqueName(uniqueName);
        setName_de(name_de);
        setName_fr(name_fr);
        setDefaultValue(defaultvalue);
    }


    /**
     * Copy from dto
     */
    public SbgParameter(Parameter dtoParameter) {
        setParameterId(dtoParameter.getParameterId());
        setFilterId(dtoParameter.getFilterId());
        setPlausiId(dtoParameter.getPlausiId());
        setExportId(dtoParameter.getExportId());
        setUniqueName(dtoParameter.getUniqueName());
        setName_de(dtoParameter.getName_de());
        setName_fr(dtoParameter.getName_fr());
        setName_it(dtoParameter.getName_it());
        setDefaultValue(dtoParameter.getDefaultValue());
        setParameterOrder(dtoParameter.getParameterOrder());
    }

    // Comparable

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Comparable#compareTo(java.lang.Object)
     */
    public int compareTo(Object o) {
        return getParameterId().compareTo(((Parameter) o).getParameterId());
    }
}
