## Plausierrors
plausierror.Missing=Feld {0} ist obligatorisch 
plausierror.NotANumber={0} muss numerisch sein
plausierror.NotADate={0} muss ein Datum sein
plausierror.NotABoolean={0} muss 0 oder 1 sein
plausierror.TooLong={0} darf höchstens {1} Stellen lang sein
plausierror.WrongLength={0} muss genau {1} Stellen lang sein
plausierror.CodeNotInCodegroup=Code {1} ist nicht in der Nomenklatur {0} vorhanden
plausierror.WrongAge=Das Alter muss zwischen {0} und {1} sein
plausierror.WrongContractDate=Das Datum des Lehrvertragsabschlusses muss im Erhebungsjahr sein
plausierror.WrongCancellationDate=Das Abbruchdatum muss im Erhebungsjahr sein
plausierror.NoburNotComplete=Die Angaben zum Ausbildungsbetrieb sind unvollständig
plausierror.NoEvent=Kein Ereignis zur Person vorhanden
plausierror.DuplicatePerson=Die durch {0} identifizierte Person ist in der Lieferung bereits vorhanden. Der Identifikator darf nur einmal verwendet werden.
plausierror.DuplicateContract=Der durch {0} identifizierte Vertrag ist in der Lieferung bereits vorhanden. Der Identifikator darf nur einmal verwendet werden.
plausierror.MissingEventForContract=Der durch {0} identifizierte Vertrag hat kein zugehöriges Ereignis mit gleicher Vertragsnummer (Laufende Lehre, Abbruch oder Abschluss).
plausierror.WrongEventForOngoingEducation=Es darf keinen Abschluss oder Abbruch zur Laufenden Lehre für den Vertrag {0} geben. 
plausierror.MoreThanOneOngoingEducation=Es darf höchstens eine laufende Lehre für eine Person geben.
plausierror.KeyAspectDoNotMatchSbfiCode=Schwerpunkt passt nicht zum Berufscode.
plausierror.WrongAhvNr=Die AHV-Nummer ist nicht korrekt
plausierror.WrongIdType=Der Identifikationstyp soll 1 (CH.AHV) sein
plausierror.ProfessionCode=Der Berufscode von Vertrag {0} stimmt nicht mit dem Vorjahr überein.

## Delivery: XML Tag Names
xml.tag.lidat.name=Jahr
## Persons: XML Tag Names
xml.tag.idnr.name=Pers-Id
xml.tag.idtyp.name=Id-Typ
xml.tag.sex.name=Geschlecht
xml.tag.dateofbirth.name=Geburtsjahr
xml.tag.newdateofbirth.name=Geburtsdatum
xml.tag.com.name=Kommentar
## Events: XML Tag Names
xml.tag.sbficode.name=SBFI-Code
xml.tag.vertnr.name=Vertrag-Nr.
xml.tag.profid.name=Berufscode
xml.tag.keyaspect.name=Schwerpunkt
xml.tag.educationyear.name=Ausbildungsjahr
xml.tag.lehrtyp.name=Bildungstyp
xml.tag.vertdat.name=Vertragsdatum
xml.tag.extyp.name=Prüfungsart
xml.tag.exnr.name=Prüfungs-Nr.
xml.tag.rep.name=Wiederholung
xml.tag.res.name=Ergebnisse
xml.tag.abdat.name=Abbruchdatum
xml.tag.abtyp.name=Abbruchsursache
xml.tag.burnr.name=BURNR
xml.tag.kantlbcode.name=Kantonaler Lehrbetriebskode
xml.tag.untname.name=Lehrbetriebsname
xml.tag.str.name=Strasse
xml.tag.strnr.name=Haus-Nr.
xml.tag.plz.name=PLZ
xml.tag.gem.name=Betriebsstandort
xml.tag.flaglbv.name=LBV

## Code Groups
codegroup.canton.name=KANTON
codegroup.sex.name=GESCHLECHT
codegroup.professioncode.name=BERUFSCODE
codegroup.sbficode.name=SBFICODE
codegroup.contracttype.name=BILDUNGSTYP
codegroup.examtype.name=PRÜFUNGSART
codegroup.examresult.name=PRÜFUNGSERGEBNIS
codegroup.cancelreason.name=ABBRUCHSURSACHE

# plausi report
plausi.report.tooManyErrors=Es gibt weitere Fehler (Maximum von {0} Fehlern überschritten)...

# Validation report
validation.Report=Validiert am {0} durch {1}:\nAnzahl validierter Datensätze: {2}\nAnzahl nicht validierter Datensätze: {3}
validation.undo.Report=Entvalidiert am {0} durch {1}:\nAnzahl validierter Datensätze: {2}\nAnzahl nicht validierter Datensätze: {3}

## JDBC errors
exception.jdbc.column.length=Ein Wert eines Attributes ist zu lang, um abgespeichert werden zu können.
