kind: Secret
apiVersion: v1
metadata:
  name: bitbucket-secret
  namespace: bit-cicd-tekton
data:
  id_rsa: Bitbucket Private Key --> see Margun KeePass
  ssh-privatekey: Bitbucket Private Key --> see Margun KeePass
type: kubernetes.io/ssh-auth