kind: Secret
apiVersion: v1
metadata:
  name: nexus-pro-docker-credentials
  namespace: bit-cicd-tekton
data:
  .dockerconfigjson: insert base64-Encoded .dockerconfigjson
type: kubernetes.io/dockerconfigjson
