package ch.admin.bfs.sbg.transfer;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;

/**
 * Action generated by MyEclipse - Hibernate Tools
 */
public class Action implements java.io.Serializable {

    private static final long serialVersionUID = -6513696769789755648L;

    // Fields    

    private Long actionid;
    private Long deliveryid;
    private Long type;
    private String actionuser;
    private Date executiondate;
    private String validationreport_de;
    private String validationreport_fr;

    // derived fields
    private Long canton;
    private Long version;
    private String plausireportname;

    // Constructors

    /** default constructor */
    public Action() {}

    /** full constructor */
    public Action(Long deliveryid, Long type, String actionuser, Date executiondate, String validationreport_de, String validationreport_fr) {
        this.deliveryid = deliveryid;
        this.type = type;
        this.actionuser = actionuser;
        this.executiondate = executiondate;
        this.validationreport_de = validationreport_de;
        this.validationreport_fr = validationreport_fr;
    }

    // Property accessors

    public Long getActionid() {
        return this.actionid;
    }

    public void setActionid(Long actionid) {
        this.actionid = actionid;
    }

    public Long getDeliveryid() {
        return this.deliveryid;
    }

    public void setDeliveryid(Long deliveryid) {
        this.deliveryid = deliveryid;
    }

    public Long getType() {
        return this.type;
    }

    public void setType(Long type) {
        this.type = type;
    }

    public String getActionuser() {
        return this.actionuser;
    }

    public void setActionuser(String actionuser) {
        this.actionuser = actionuser;
    }

    public Date getExecutiondate() {
        return this.executiondate;
    }

    public void setExecutiondate(Date executiondate) {
        this.executiondate = executiondate;
    }

    public String getValidationreport_de() {
        return this.validationreport_de;
    }

    public void setValidationreport_de(String validationreport) {
        this.validationreport_de = validationreport;
    }

    public String getValidationreport_fr() {
        return this.validationreport_fr;
    }

    public void setValidationreport_fr(String validationreport) {
        this.validationreport_fr = validationreport;
    }

    public Long getCanton() {
        return this.canton;
    }

    public void setCanton(Long canton) {
        this.canton = canton;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getPlausireportname() {
        return this.plausireportname;
    }

    public void setPlausireportname(String filename) {
        this.plausireportname = filename;
    }
}
