package ch.admin.bfs.sbg.transfer;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import ch.bfs.meb.sbg.server.integration.dto.SbgEvent;
import lombok.Getter;
import lombok.Setter;

/**
 * AbstractEvent generated by MyEclipse - Hibernate Tools
 */

public class Event implements java.io.Serializable {

    private static final long serialVersionUID = -6573696769789555648L;

    // Fields
    private Long eventid;
    private Long pid;
    private Long canton;
    private Long version;
    private Long type;

    /**
     * Code for SBFI ("Staatssekretariat fuer Bildung, Forschung und Innovation") State Secretariat for Education, Research and Innovation
     */
    @Getter
    @Setter
    private Long sbfiCode;

    private Long contractNr;
    private Long professionCode;
    private Long contractType;
    private Date contractDate;
    private Long educationYear;
    private Long examType;
    private Long examNr;
    private Long examRepetition;
    private Long examResult;
    private Long cancelReason;
    private Date cancelDate;
    private Long burnr;
    private String kantLbCode;
    private Long keyAspect;
    private String userComment;
    private String firmName;
    private String firmStreet;
    private String firmStreetNr;
    private Long firmPlz;
    private String firmMunicipality;
    private boolean flagLbv;
    private Long plausiStatus;
    private boolean isValidated;
    private String modUser;
    private Date modDate;
    private List<Plausierror> plausiErrors;

    // Constructors

    /**
     * default constructor
     */
    public Event() {}

    /**
     * Construct with persistent object SbgEvent - Obsolete if webservice interface is changed to SbgEvent
     *
     * @param anEvent
     */
    public Event(SbgEvent anEvent) {
        setEventid(anEvent.getEventid());
        setPid(anEvent.getPid());
        setCanton(anEvent.getCanton());
        setVersion(anEvent.getVersion());
        setType(anEvent.getType());
        setSbfiCode(anEvent.getSbfiCode());
        setContractNr(anEvent.getContractNr());
        setProfessionCode(anEvent.getProfessionCode());
        setContractType(anEvent.getContractType());
        setContractDate(anEvent.getContractDate());
        setEducationYear(anEvent.getEducationYear());
        setExamType(anEvent.getExamType());
        setExamNr(anEvent.getExamNr());
        setExamRepetition(anEvent.getExamRepetition());
        setExamResult(anEvent.getExamResult());
        setCancelReason(anEvent.getCancelReason());
        setCancelDate(anEvent.getCancelDate());
        setBurnr(anEvent.getBurnr());
        setKantLbCode(anEvent.getKantLbCode());
        setKeyAspect(anEvent.getKeyAspect());
        setUserComment(anEvent.getUserComment());
        setFirmName(anEvent.getFirmName());
        setFirmStreet(anEvent.getFirmStreet());
        setFirmStreetNr(anEvent.getFirmStreetNr());
        setFirmPlz(anEvent.getFirmPlz());
        setFirmMunicipality(anEvent.getFirmMunicipality());
        setFlagLbv(anEvent.getFlagLbv());
        setPlausiStatus(anEvent.getPlausiStatus());
        setIsValidated(anEvent.getIsValidated());
        setModUser(anEvent.getModUser());
        setModDate(anEvent.getModDate());

        this.plausiErrors = new ArrayList<Plausierror>();
        if (anEvent.getPlausierrors() != null) {
            for (Plausierror plausiError : anEvent.getPlausierrors()) {
                plausiErrors.add(plausiError);
            }
        }
        Map<Long, Plausierror> unique = new HashMap<>();
        for (Plausierror p : this.plausiErrors) {
            unique.put(p.getPlausiId(), p);
        }
        this.plausiErrors = new ArrayList<>(unique.values());
    }

    public Event(Event anEvent, List<Plausierror> persistPlausiErrors) {
        setEventid(anEvent.getEventid());
        setPid(anEvent.getPid());
        setCanton(anEvent.getCanton());
        setVersion(anEvent.getVersion());
        setType(anEvent.getType());
        setSbfiCode(anEvent.getSbfiCode());
        setContractNr(anEvent.getContractNr());
        setProfessionCode(anEvent.getProfessionCode());
        setContractType(anEvent.getContractType());
        setContractDate(anEvent.getContractDate());
        setEducationYear(anEvent.getEducationYear());
        setExamType(anEvent.getExamType());
        setExamNr(anEvent.getExamNr());
        setExamRepetition(anEvent.getExamRepetition());
        setExamResult(anEvent.getExamResult());
        setCancelReason(anEvent.getCancelReason());
        setCancelDate(anEvent.getCancelDate());
        setBurnr(anEvent.getBurnr());
        setKantLbCode(anEvent.getKantLbCode());
        setKeyAspect(anEvent.getKeyAspect());
        setUserComment(anEvent.getUserComment());
        setFirmName(anEvent.getFirmName());
        setFirmStreet(anEvent.getFirmStreet());
        setFirmStreetNr(anEvent.getFirmStreetNr());
        setFirmPlz(anEvent.getFirmPlz());
        setFirmMunicipality(anEvent.getFirmMunicipality());
        setFlagLbv(anEvent.getFlagLbv());
        setPlausiStatus(anEvent.getPlausiStatus());
        setIsValidated(anEvent.getIsValidated());
        setModUser(anEvent.getModUser());
        setModDate(anEvent.getModDate());

        this.plausiErrors = new ArrayList<Plausierror>();
        if (persistPlausiErrors != null) {
            for (Plausierror plausiError : persistPlausiErrors) {
                plausiErrors.add(new Plausierror(plausiError));
            }
        }
        Map<Long, Plausierror> unique = new HashMap<>();
        for (Plausierror p : this.plausiErrors) {
            unique.put(p.getPlausiId(), p);
        }
        this.plausiErrors = new ArrayList<>(unique.values());
    }

    /**
     * full constructor
     */
    public Event(Long pid, Long contractNr, Long contractType, Long professionCode) {
        this.pid = pid;
        this.contractNr = contractNr;
        this.professionCode = professionCode;
        this.contractType = contractType;
    }

    // Property accessors
    public Long getEventid() {
        return this.eventid;
    }

    public void setEventid(Long eventid) {
        this.eventid = eventid;
    }

    public Long getPid() {
        return this.pid;
    }

    public void setPid(Long pid) {
        this.pid = pid;
    }

    public Long getCanton() {
        return this.canton;
    }

    public void setCanton(Long canton) {
        this.canton = canton;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Long getContractNr() {
        return this.contractNr;
    }

    public void setContractNr(Long contractNr) {
        this.contractNr = contractNr;
    }

    public String getUserComment() {
        return this.userComment;
    }

    public void setUserComment(String userComment) {
        this.userComment = userComment;
    }

    public String getModUser() {
        return this.modUser;
    }

    public void setModUser(String modUser) {
        this.modUser = modUser;
    }

    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    public Long getProfessionCode() {
        return this.professionCode;
    }

    public void setProfessionCode(Long professionCode) {
        this.professionCode = professionCode;
    }

    public Long getContractType() {
        return this.contractType;
    }

    public void setContractType(Long contractType) {
        this.contractType = contractType;
    }

    public Date getContractDate() {
        return this.contractDate;
    }

    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    public Long getBurnr() {
        return this.burnr;
    }

    public void setBurnr(Long burnr) {
        this.burnr = burnr;
    }

    public Long getEducationYear() {
        return this.educationYear;
    }

    public void setEducationYear(Long educationYear) {
        this.educationYear = educationYear;
    }

    public Long getExamType() {
        return this.examType;
    }

    public void setExamType(Long examType) {
        this.examType = examType;
    }

    public Long getExamNr() {
        return this.examNr;
    }

    public void setExamNr(Long examNr) {
        this.examNr = examNr;
    }

    public Long getExamRepetition() {
        return this.examRepetition;
    }

    public void setExamRepetition(Long examRepetition) {
        this.examRepetition = examRepetition;
    }

    public Long getExamResult() {
        return this.examResult;
    }

    public void setExamResult(Long examResult) {
        this.examResult = examResult;
    }

    public Long getCancelReason() {
        return this.cancelReason;
    }

    public void setCancelReason(Long cancelReason) {
        this.cancelReason = cancelReason;
    }

    public Date getCancelDate() {
        return this.cancelDate;
    }

    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    public String getKantLbCode() {
        return kantLbCode;
    }

    public void setKantLbCode(String kantLbCode) {
        this.kantLbCode = kantLbCode;
    }

    public String getFirmName() {
        return this.firmName;
    }

    public void setFirmName(String firmName) {
        this.firmName = firmName;
    }

    public String getFirmStreet() {
        return this.firmStreet;
    }

    public void setFirmStreet(String firmStreet) {
        this.firmStreet = firmStreet;
    }

    public String getFirmStreetNr() {
        return this.firmStreetNr;
    }

    public void setFirmStreetNr(String firmStreetNr) {
        this.firmStreetNr = firmStreetNr;
    }

    public Long getFirmPlz() {
        return this.firmPlz;
    }

    public void setFirmPlz(Long firmPlz) {
        this.firmPlz = firmPlz;
    }

    public String getFirmMunicipality() {
        return this.firmMunicipality;
    }

    public void setFirmMunicipality(String firmMunicipality) {
        this.firmMunicipality = firmMunicipality;
    }

    public boolean getFlagLbv() {
        return this.flagLbv;
    }

    public void setFlagLbv(boolean flagLbv) {
        this.flagLbv = flagLbv;
    }

    public Long getKeyAspect() {
        return this.keyAspect;
    }

    public void setKeyAspect(Long keyAspect) {
        this.keyAspect = keyAspect;
    }

    public Long getPlausiStatus() {
        return this.plausiStatus;
    }

    public void setPlausiStatus(Long plausiStatus) {
        this.plausiStatus = plausiStatus;
    }

    public void setIsValidated(boolean isValidated) {
        this.isValidated = isValidated;
    }

    public boolean getIsValidated() {
        return this.isValidated;
    }

    public Long getType() {
        return type;
    }

    public void setType(Long type) {
        this.type = type;
    }

    public List<Plausierror> getPlausiErrors() {
        if (this.plausiErrors == null) {
            this.plausiErrors = new ArrayList<Plausierror>();
        }
        return this.plausiErrors;
    }

    public void setPlausiErrors(List<Plausierror> plausiErrors) {
        this.plausiErrors = plausiErrors;
    }
}