package ch.admin.bfs.sbg.transfer;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;

import ch.bfs.meb.sbg.server.integration.dto.SbgParameter;
import lombok.Data;

/**
 * Macro generated by MyEclipse - Hibernate Tools
 */
@Data
@Entity
@Table(name = "MACRO")
@GenericGenerator(name = "filterseqgen", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
        @org.hibernate.annotations.Parameter(name = "sequence_name", value = "SBGSEQ"),
        @org.hibernate.annotations.Parameter(name = "increment_size", value = "100"),
        @org.hibernate.annotations.Parameter(name = "optimizer", value = "pooled-lo") })
public class Macro implements java.io.Serializable {
    public static final Long MACRO_SIMPLEPLAUSI = 0L;
    public static final Long MACRO_COMPLEXPLAUSI = 1L;
    public static final Long MACRO_IS_NOT_CONFIRMABLE = 0L;
    public static final Long MACRO_IS_CONFIRMABLE = 1L;
    // Constants
    private static final long serialVersionUID = -6513646769389555648L;

    // Fields
    @Id
    @Column(name = "MACROID", precision = 22)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "filterseqgen")
    private Long macroid;

    @Column(precision = 2)
    private Long type;

    @Column(precision = 2)
    private Long objecttype;

    @Column(name = "NAME_D", length = 50)
    private String name_de;

    @Column(name = "NAME_F", length = 50)
    private String name_fr;

    @Column(name = "DESCRIPTION_D", length = 252)
    private String description_de;

    @Column(name = "DESCRIPTION_F", length = 252)
    private String description_fr;

    @Column(length = 1020)
    private String source;

    @Column(name = "MACROORDER", precision = 2)
    private Long order;

    @Column(precision = 2)
    private Long authorisationlevel;

    @Column(precision = 1)
    private Long isactive;

    @Column(precision = 1)
    private Long isconfirmable;

    @Column(length = 50)
    private String moduser;

    @Column
    private Date moddate;

    @OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.EAGER, orphanRemoval = true)
    @JoinColumn(name = "macroid")
    @OrderBy("parameterOrder, parameterId")
    private List<SbgParameter> parameters = new ArrayList<SbgParameter>();

    /**
     * default constructor.
     */
    public Macro() {}

    /**
     * constructor to clone macro.
     */
    public Macro(Macro macro) {
        this.macroid = macro.getMacroid();
        this.type = macro.getType();
        this.objecttype = macro.getObjecttype();
        this.name_de = macro.getName_de();
        this.name_fr = macro.getName_fr();
        this.description_de = macro.getDescription_de();
        this.description_fr = macro.getDescription_fr();
        this.source = macro.getSource();
        this.order = macro.getOrder();
        this.authorisationlevel = macro.getAuthorisationlevel();
        this.isactive = macro.getIsactive();
        this.isconfirmable = macro.getIsconfirmable();
        this.moduser = macro.getModuser();
        this.moddate = macro.getModdate();
        this.parameters = macro.getParameters();
    }

    /**
     * full constructor.
     */
    public Macro(Long type, Long objecttype, String name_de, String name_fr, String description_de, String description_fr, String source, Long order,
            Long authorisationlevel, Long isactive, Long isconfirmable, String moduser, Date moddate, List<SbgParameter> parameters) {
        this.type = type;
        this.objecttype = objecttype;
        this.name_de = name_de;
        this.name_fr = name_fr;
        this.description_de = description_de;
        this.description_fr = description_fr;
        this.source = source;
        this.order = order;
        this.authorisationlevel = authorisationlevel;
        this.isactive = isactive;
        this.isconfirmable = isconfirmable;
        this.moduser = moduser;
        this.moddate = moddate;
        this.parameters = parameters;
    }
}