package ch.admin.bfs.sbg.transfer;

import java.util.Date;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * AbstractPerson generated by MyEclipse - Hibernate Tools
 */

public class Person implements java.io.Serializable {

    private static final long serialVersionUID = -6513692769789515648L;

    // Fields
    private Long pid;
    private Long canton;
    private Long version;
    private Long deliveryId;
    private Long idType;
    private Long id;
    private Long sex;
    private Long birthDate;
    private Date newBirthDate;
    private String userComment;
    private String deliveryText;
    private String modUser;
    private Date modDate;
    private String validationUser;
    private Date validationDate;
    private boolean isToDelete;
    private Long plausiStatus;
    private Long status;
    private Set<Plausierror> plausiErrors = new LinkedHashSet<Plausierror>();

    // Constructors

    /**
     * default constructor
     */
    public Person() {}

    /**
     * full constructor
     */
    public Person(Long deliveryId, Long id) {
        this.deliveryId = deliveryId;
        this.id = id;
    }

    public Person(Person aPerson, List<Plausierror> plausiErrorList) {
        setPid(aPerson.getPid());
        setDeliveryId(aPerson.getDeliveryId());
        setCanton(aPerson.getCanton());
        setVersion(aPerson.getVersion());
        setIdType(aPerson.getIdType());
        setId(aPerson.getId());
        setSex(aPerson.getSex());
        setBirthDate(aPerson.getBirthDate());
        setNewBirthDate(aPerson.getNewBirthDate());
        setUserComment(aPerson.getUserComment());
        setDeliveryText(aPerson.getDeliveryText());
        setModUser(aPerson.getModUser());
        setModDate(aPerson.getModDate());
        setValidationUser(aPerson.getValidationUser());
        setValidationDate(aPerson.getValidationDate());
        setIsToDelete(aPerson.getIsToDelete());
        setPlausiStatus(aPerson.getPlausiStatus());
        setStatus(aPerson.getStatus());

        if (plausiErrors != null) {
            for (Plausierror plausiError : plausiErrorList) {
                plausiErrors.add(new Plausierror(plausiError));
            }
        }
    }

    // Property accessors
    public Long getPid() {
        return this.pid;
    }

    public void setPid(Long pid) {
        this.pid = pid;
    }

    public Long getCanton() {
        return this.canton;
    }

    public void setCanton(Long canton) {
        this.canton = canton;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Long getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Long birthDate) {
        this.birthDate = birthDate;
    }

    public Date getNewBirthDate() {
        return newBirthDate;
    }

    public void setNewBirthDate(Date newBirthDate) {
        this.newBirthDate = newBirthDate;
    }

    public Long getDeliveryId() {
        return deliveryId;
    }

    public void setDeliveryId(Long deliveryId) {
        this.deliveryId = deliveryId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeliveryText() {
        return deliveryText;
    }

    public void setDeliveryText(String deliveryText) {
        this.deliveryText = deliveryText;
    }

    public Long getIdType() {
        return idType;
    }

    public void setIdType(Long idType) {
        this.idType = idType;
    }

    public boolean getIsToDelete() {
        return isToDelete;
    }

    public void setIsToDelete(boolean isToDelete) {
        this.isToDelete = isToDelete;
    }

    public Date getModDate() {
        return modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
    }

    public String getModUser() {
        return modUser;
    }

    public void setModUser(String modUser) {
        this.modUser = modUser;
    }

    public Long getPlausiStatus() {
        return plausiStatus;
    }

    public void setPlausiStatus(Long plausiStatus) {
        this.plausiStatus = plausiStatus;
    }

    public Long getSex() {
        return sex;
    }

    public void setSex(Long sex) {
        this.sex = sex;
    }

    public Long getStatus() {
        return status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public String getUserComment() {
        return userComment;
    }

    public void setUserComment(String userComment) {
        this.userComment = userComment;
    }

    public Date getValidationDate() {
        return validationDate;
    }

    public void setValidationDate(Date validationDate) {
        this.validationDate = validationDate;
    }

    public String getValidationUser() {
        return validationUser;
    }

    public void setValidationUser(String validationUser) {
        this.validationUser = validationUser;
    }

    public Set<Plausierror> getPlausiErrors() {
        return this.plausiErrors;
    }

    public void setPlausiErrors(Set<Plausierror> plausiErrors) {
        this.plausiErrors = plausiErrors;
    }
}