package ch.admin.bfs.sbg.transfer;

import java.util.*;

import org.springframework.security.core.context.SecurityContextHolder;

import ch.admin.bfs.sbg.db.dao.MacroDAO;
import ch.bfs.meb.security.MebUser;

/**
 * Plausierror generated by MyEclipse - Hibernate Tools
 */

public class Plausierror implements java.io.Serializable {

    private static final long serialVersionUID = -6513646765789555648L;

    // Fields

    private Long errorid;
    private Long deliveryid;
    private Long pid;
    private Long eventid;
    private Long macroid;
    private String errormsg_de;
    private String errormsg_fr;
    private String reportdata;
    private boolean isconfirmed;
    private String confirmid;
    private String moduser;
    private Date moddate;
    private boolean isToDelete;

    // derived fields
    private boolean isConfirmable;
    private String macroName_de;
    private String macroName_fr;

    private String _person_idType;
    private String _person_id;
    private Long _event_type;
    private String _event_id;

    public static final Boolean CONFIRMED = Boolean.TRUE;
    public static final Boolean NOT_CONFIRMED = Boolean.FALSE;

    // Constructors

    /**
     * default constructor
     */
    public Plausierror() {}

    public Plausierror(Plausierror anError) {
        setErrorId(anError.getErrorId());
        setDeliveryId(anError.getDeliveryId());
        setPid(anError.getPid());
        setEventId(anError.getEventId());
        setPlausiId(anError.getPlausiId());
        setErrorMsg_de(anError.getErrorMsg_de());
        setErrorMsg_fr(anError.getErrorMsg_fr());
        setReportData(anError.getReportData());
        setIsConfirmed(anError.getIsConfirmed());
        setConfirmId(anError.getConfirmId());
        setIsToDelete(anError.getIsToDelete());
        setModification_user(anError.getModification_user());
        setModification_date(anError.getModification_date());
        setPlausiName_de(anError.getPlausiName_de());
        setPlausiName_fr(anError.getPlausiName_fr());
    }

    public static List<Plausierror> updatePlausiErrorsData(Set<Plausierror> psistPlausiErrors, List<Plausierror> dataPlausiErrors) {
        List<Plausierror> newPlausiErrors = new ArrayList<Plausierror>();
        HashMap<Long, Plausierror> dataPlausiErrorsMap = new HashMap<Long, Plausierror>();
        if (dataPlausiErrors != null) {
            for (Plausierror plausiError : dataPlausiErrors) {
                dataPlausiErrorsMap.put(plausiError.getErrorId(), plausiError);
            }
        }

        String userEmail = ((MebUser) SecurityContextHolder.getContext().getAuthentication().getPrincipal()).getEmail();
        for (Plausierror psistPlausiError : psistPlausiErrors) {
            if (dataPlausiErrors != null) {
                Plausierror plausiError = dataPlausiErrorsMap.get(psistPlausiError.getErrorId());
                if (plausiError != null) {
                    Plausierror newPlausiError = new Plausierror(plausiError);
                    // confirmed state changed, update modification data
                    if (plausiError.getIsConfirmed() != psistPlausiError.getIsConfirmed()) {
                        newPlausiError.setModification_user(userEmail);
                        newPlausiError.setModification_date(new Date());
                    }
                    newPlausiErrors.add(newPlausiError);
                } else {
                    newPlausiErrors.add(new Plausierror(psistPlausiError));
                }
            } else {
                newPlausiErrors.add(new Plausierror(psistPlausiError));
            }
        }

        return newPlausiErrors;
    }

    // Property accessors

    public Long getErrorId() {
        return this.errorid;
    }

    public void setErrorId(Long errorid) {
        this.errorid = errorid;
    }

    public Long getDeliveryId() {
        return this.deliveryid;
    }

    public void setDeliveryId(Long deliveryid) {
        this.deliveryid = deliveryid;
    }

    public Long getPid() {
        return this.pid;
    }

    public void setPid(Long pid) {
        this.pid = pid;
    }

    public Long getEventId() {
        return this.eventid;
    }

    public void setEventId(Long eventid) {
        this.eventid = eventid;
    }

    public Long getPlausiId() {
        return this.macroid;
    }

    public void setPlausiId(Long macroid) {
        this.macroid = macroid;
    }

    public String getErrorMsg_de() {
        return this.errormsg_de;
    }

    public void setErrorMsg_de(String errormsg_de) {
        this.errormsg_de = errormsg_de;
    }

    public String getErrorMsg_fr() {
        return this.errormsg_fr;
    }

    public void setErrorMsg_fr(String errormsg_fr) {
        this.errormsg_fr = errormsg_fr;
    }

    public boolean getIsConfirmed() {
        return this.isconfirmed;
    }

    public void setIsConfirmed(boolean isconfirmed) {
        this.isconfirmed = isconfirmed;
    }

    public String getConfirmId() {
        return this.confirmid;
    }

    public void setConfirmId(String confirmid) {
        this.confirmid = confirmid;
    }

    public String getModification_user() {
        return this.moduser;
    }

    public void setModification_user(String moduser) {
        this.moduser = moduser;
    }

    public Date getModification_date() {
        return this.moddate;
    }

    public void setModification_date(Date moddate) {
        this.moddate = moddate;
    }

    public boolean getIsToDelete() {
        return isToDelete;
    }

    public void setIsToDelete(boolean isToDelete) {
        this.isToDelete = isToDelete;
    }

    public boolean isConfirmable() {
        return isConfirmable;
    }

    public void setConfirmable(boolean isConfirmable) {
        this.isConfirmable = isConfirmable;
    }

    public String getPlausiName_de() {
        return this.macroName_de;
    }

    public void setPlausiName_de(String name_de) {
        this.macroName_de = name_de;
    }

    public String getPlausiName_fr() {
        return this.macroName_fr;
    }

    public void setPlausiName_fr(String name_fr) {
        this.macroName_fr = name_fr;
    }

    public void loadMacroData(MacroDAO macroDAO) {
        Macro plausi = (Macro) macroDAO.load(Macro.class, macroid);
        loadMacroData(plausi);
    }

    public void loadMacroData(List<Macro> allPlausis) {
        Macro plausi = null;
        for (Macro m : allPlausis) {
            if (m.getMacroid().equals(this.macroid)) {
                plausi = m;
                break;
            }
        }
        loadMacroData(plausi);
    }

    public void loadMacroData(Macro plausi) {
        isConfirmable = plausi.getIsconfirmable().equals(Macro.MACRO_IS_CONFIRMABLE);
        macroName_de = plausi.getName_de() != null ? plausi.getName_de() : "";
        macroName_fr = plausi.getName_fr() != null ? plausi.getName_fr() : "";
    }

    public String getReportData() {
        return reportdata;
    }

    public void setReportData(String reportdata) {
        this.reportdata = reportdata;
    }

    public void addEventInfo(Long eventType, String contractNr) {
        _event_type = eventType;
        _event_id = contractNr;
    }

    public void addPersonInfo(String idType, String id) {
        _person_idType = idType;
        _person_id = id;
    }

    public String getPerson_idType() {
        return _person_idType;
    }

    public String getPerson_id() {
        return _person_id;
    }

    public Long getEvent_type() {
        return _event_type;
    }

    public String getEvent_id() {
        return _event_id;
    }

    // Get a unique id for the error
    public String getLogicalKey() {
        String errorKey = "";

        if (getPid() != null && (_person_idType == null || _person_id == null)) {
            // Incomplete logical person id -> take pid to make the key unique
            errorKey = errorKey + getPid().toString();
        } else {
            errorKey = errorKey + (_person_idType == null ? "" : _person_idType);
            errorKey = errorKey + (_person_id == null ? "" : "_" + _person_id);
        }

        if (getEventId() != null && (_event_type == null || _event_id == null)) {
            // Incomplete logical event id -> take eventId to make the key unique
            errorKey = errorKey + "_" + getEventId().toString();
        } else {
            errorKey = errorKey + (_event_type == null ? "" : "_" + _event_type.toString());
            errorKey = errorKey + (_event_id == null ? "" : "_" + _event_id);
        }
        errorKey = errorKey + (getPlausiId() == null ? "" : "_" + getPlausiId().toString());
        errorKey = errorKey + (getConfirmId() == null ? "" : "#" + getConfirmId());

        return errorKey;
    }
}