package ch.admin.bfs.sbg.transfer;
// Generated by MyEclipse - Hibernate Tools

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Transient;

import ch.bfs.meb.util.CodegroupUtility;

/**
 * Delivery generated by MyEclipse - Hibernate Tools
 */
public class SbgDelivery implements java.io.Serializable {

    private static final long serialVersionUID = -6513646769789555648L;

    // Constants
    public final static Long DELIVERY_NOT_LOCKED = 0L;
    public final static Long DELIVERY_LOCKED = 1L;
    public final static Long DELIVERY_PENDING_ACTION = 2L;

    // Fields
    private Long deliveryid;
    private Long canton;
    private Long version;
    private String deliveryuser;
    private Date deliverydate;
    private Long plausistatus;
    private Long status;
    private Long islocked;
    private List<Plausierror> plausiErrors;

    // persons and events
    private Integer personPlausiOk;
    private Integer personPlausiNotOk;
    private Integer eventPlausiOk;
    private Integer eventPlausiNotOk;
    private Integer personValid;
    private Integer personNotValid;

    // Transient
    private boolean _creatingReport;

    // Constructors

    /**
     * default constructor
     */
    public SbgDelivery() {
        resetPlausiNumbers();
    }

    /**
     * full constructor
     */
    public SbgDelivery(Long canton, Long version, String deliveryUserEmail, Date deliverydate, Long plausistatus, Long status, Long islocked) {
        this.canton = canton;
        this.version = version;
        this.deliveryuser = deliveryUserEmail;
        this.deliverydate = deliverydate;
        this.plausistatus = plausistatus;
        this.status = status;
        this.islocked = islocked;

        resetPlausiNumbers();
    }

    public void resetPlausiNumbers() {
        personPlausiOk = new Integer(0);
        personPlausiNotOk = new Integer(0);
        eventPlausiOk = new Integer(0);
        eventPlausiNotOk = new Integer(0);
        personValid = new Integer(0);
        personNotValid = new Integer(0);
    }

    public void addPlausiPersons(Long plausiStatus, Long status, Long nrPersons) {
        if ((plausiStatus != null)
                && (plausiStatus.equals(CodegroupUtility.SBG_PLAUSISTATUS_VALID) || plausiStatus.equals(CodegroupUtility.SBG_PLAUSISTATUS_CONFIRMED))) {
            personPlausiOk += (int) (long) nrPersons;
        } else {
            personPlausiNotOk += (int) (long) nrPersons;
        }
        if ((status != null) && status.equals(CodegroupUtility.SBG_PERSONSTATUS_VALIDATED)) {
            personValid += (int) (long) nrPersons;
        } else {
            personNotValid += (int) (long) nrPersons;
        }
    }

    public void addPlausiEvents(Long plausiStatus, Long nrEvents) {
        if ((plausiStatus != null)
                && (plausiStatus.equals(CodegroupUtility.SBG_PLAUSISTATUS_VALID) || plausiStatus.equals(CodegroupUtility.SBG_PLAUSISTATUS_CONFIRMED))) {
            eventPlausiOk += (int) (long) nrEvents;
        } else {
            eventPlausiNotOk += (int) (long) nrEvents;
        }
    }

    // Property accessors

    public Long getDeliveryid() {
        return this.deliveryid;
    }

    public void setDeliveryid(Long deliveryid) {
        this.deliveryid = deliveryid;
    }

    public Long getCanton() {
        return this.canton;
    }

    public void setCanton(Long canton) {
        this.canton = canton;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getDeliveryuser() {
        return this.deliveryuser;
    }

    public void setDeliveryuser(String deliveryuser) {
        this.deliveryuser = deliveryuser;
    }

    public Date getDeliverydate() {
        return this.deliverydate;
    }

    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }

    public Long getPlausistatus() {
        return this.plausistatus;
    }

    public void setPlausistatus(Long plausistatus) {
        this.plausistatus = plausistatus;
    }

    public Long getStatus() {
        return this.status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public Long getIslocked() {
        return this.islocked;
    }

    public void setIslocked(Long islocked) {
        this.islocked = islocked;
    }

    public List<Plausierror> getPlausiErrors() {
        if (this.plausiErrors == null) {
            this.plausiErrors = new ArrayList<Plausierror>();
        }
        return this.plausiErrors;
    }

    public void setPlausiErrors(List<Plausierror> plausiErrors) {
        this.plausiErrors = plausiErrors;
    }

    public String getNrplausiperson() {
        return personPlausiOk.toString() + "/" + new Integer(personPlausiOk + personPlausiNotOk).toString();
    }

    public void setNrplausiperson(String nrplausiperson) {}

    public String getNrplausievent() {
        return eventPlausiOk.toString() + "/" + new Integer(eventPlausiOk + eventPlausiNotOk).toString();
    }

    public void setNrplausievent(String nrplausievent) {}

    public String getNotvalid() {
        return personNotValid.toString() + "/" + new Integer(personNotValid + personValid).toString();
    }

    public void setNotvalid(String notvalid) {}

    /**
     * @return the creatingReport
     */

    @Transient
    public boolean isCreatingReport() {
        return _creatingReport;
    }

    /**
     * @param creatingReport the creatingReport to set
     */
    public void setCreatingReport(boolean creatingReport) {
        _creatingReport = creatingReport;
    }
}
