# ExternalSecret - external Vault instance
{{- if and (.Values.global).secrets (.Values.global).secrets.externalStore (.Values.global).secrets.externalStore.enabled }}
  {{- if and (.Values.global).secrets.externalStore.paths (.Values.global).secrets.externalStore.paths.bitbucket }}
---
# ExternalSecret: BitBucket
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-ex-bitbucket-secret
spec:
  secretStoreRef:
    name: cop-{{ (.Values.global).secrets.externalStore.paths.bitbucket.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 1440m0s

  target:
    name: '{{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-bitbucket-secret'
    creationPolicy: Owner
    template:
      engineVersion: v2
      # for Tekton
      type: kubernetes.io/ssh-auth
      metadata:
        annotations:
          # to be recognized from Tekton
          tekton.dev/git-0: bitbucket.bit.admin.ch
      data:
        # for Tekton
        ssh-privatekey: '{{ `{{ .gitkey }}` }}'
        id_rsa: |
          {{ `{{ .gitkey }}` }}
        known_hosts: bitbucket.bit.admin.ch ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfO3Gh1kORpv+Zoeggwas8Tfn93QBhXSchZP5Po7XpiATnf+e9E/goZ214UuWBSkHzqy5tico4Jkk9l1uDedDXR9wxfK1xzLUPYsiUjtThkwChaEFawyWetKjzqVOKrZknZuRxUkDdH1oK0yj7uqWd7VNA5zCsVjstVxK6XF5v3wQP17xtT24imrUeXIdcmRC3IecPnlJ0KzfXNc0KP72t6/+7nfsFCft7gVp1oS4xG7Cff7AbO0I13w9gLvXk5hfkRu2YkNG0305YghETo1s8xXGHJFx7gXBXXch2m5+OlirSGsJZXLojfX0fcVvbIZUzWy3S4XRU7y1OjhJlMTVV

  data:
    - secretKey: gitkey
      remoteRef:
        key: {{ (.Values.global).secrets.externalStore.paths.bitbucket.id }}
        property: {{ (.Values.global).secrets.externalStore.paths.bitbucket.property | default "ssh" }}
  {{- end }}
  {{- if and (.Values.global).secrets.externalStore.paths (.Values.global).secrets.externalStore.paths.bitbucketAccessToken }}
---
# ExternalSecret: BitBucket Webhook
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-ex-bitbucket-accesstoken
spec:
  secretStoreRef:
    name: cop-{{ (.Values.global).secrets.externalStore.paths.bitbucketAccessToken.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 1440m0s

  target:
    name: '{{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-bitbucket-accesstoken'
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accesstoken: '{{ `{{ .accesstoken }}` }}'

  data:
    - secretKey: accesstoken
      remoteRef:
        key: {{ (.Values.global).secrets.externalStore.paths.bitbucketAccessToken.id }}
        property: {{ (.Values.global).secrets.externalStore.paths.bitbucketAccessToken.property | default "accesstoken" }}
  {{- end }}

  {{- if and (.Values.global).secrets.externalStore.paths (.Values.global).secrets.externalStore.paths.tektonDeploymentWebhookAccessToken }}
---
# ExternalSecret: Deployment Webhook
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-ex-webhook-deployment-accesstoken
spec:
  secretStoreRef:
    name: cop-{{ (.Values.global).secrets.externalStore.paths.tektonDeploymentWebhookAccessToken.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 1440m0s

  target:
    name: '{{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-webhook-deployment-accesstoken'
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        tektonWebhookAccessToken: '{{ `{{ .tektonDeploymentWebhookAccessToken }}` }}'

  data:
    - secretKey: tektonDeploymentWebhookAccessToken
      remoteRef:
        key: {{ (.Values.global).secrets.externalStore.paths.tektonDeploymentWebhookAccessToken.id }}
        property: {{ (.Values.global).secrets.externalStore.paths.tektonDeploymentWebhookAccessToken.property | default "tektonDeploymentWebhookAccessToken" }}
  {{- end }}
 {{- if and (.Values.global).secrets.externalStore.paths (.Values.global).secrets.externalStore.paths.messageContractAuth }}
---
# ExternalSecret: Message Contract Service Auth Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-ex-message-contract-service-secret
spec:
  secretStoreRef:
    name: cop-{{ (.Values.global).secrets.externalStore.paths.messageContractAuth.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 1440m0s

  target:
    name: '{{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-message-contract-service-secret'
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secret: '{{ `{{ .secret }}` }}'

  data:
    - secretKey: secret
      remoteRef:
        key: {{ (.Values.global).secrets.externalStore.paths.messageContractAuth.id }}
        property: {{ (.Values.global).secrets.externalStore.paths.messageContractAuth.property | default "secret" }}
  {{- end }}
  {{- if and (.Values.global).secrets.externalStore.paths (.Values.global).secrets.externalStore.paths.udeploy }}
  ---
  # ExternalSecret: BitBucket Webhook
  apiVersion: external-secrets.io/v1
  kind: ExternalSecret
  metadata:
    annotations:
      {{- include "java-pipeline.annotations" . | nindent 4 }}
    name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-ex-udeploy-accesstoken
  spec:
    secretStoreRef:
      name: cop-{{ (.Values.global).secrets.externalStore.paths.udeploy.vault }}
      kind: ClusterSecretStore

    # Refresh: daily
    refreshInterval: 1440m0s

    target:
      name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-udeploy-accesstoken
      creationPolicy: Owner
      template:
        engineVersion: v2
        data:
          accesstoken: '{{ `{{ .accesstoken }}` }}'

    data:
      - secretKey: accesstoken
        remoteRef:
          key: {{ (.Values.global).secrets.paths.udeploy.id }}
          property: {{ (.Values.global).secrets.externalStore.paths.udeploy.property | default "accesstoken" }}
  {{- end }}
  {{- if and (.Values.global).secrets.externalStore.paths (.Values.global).secrets.externalStore.paths.tektonWebhookAccessToken }}
---
# ExternalSecret: BitBucket Webhook
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-ex-webhook-accesstoken
spec:
  secretStoreRef:
    name: cop-{{ (.Values.global).secrets.externalStore.paths.tektonWebhookAccessToken.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 1440m0s

  target:
    name: '{{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-webhook-accesstoken'
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        tektonWebhookAccessToken: '{{ `{{ .tektonWebhookAccessToken }}` }}'

  data:
    - secretKey: tektonWebhookAccessToken
      remoteRef:
        key: {{ (.Values.global).secrets.externalStore.paths.tektonWebhookAccessToken.id }}
        property: {{ (.Values.global).secrets.externalStore.paths.tektonWebhookAccessToken.property | default "tektonWebhookAccessToken" }}
  {{- end }}

  {{- if and (.Values.global).secrets.externalStore.paths (.Values.global).secrets.externalStore.paths.mavenTaskAuthSecrets }}
---
# ExternalSecret: maven task Auth Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-ex-maven-task-auth-secrets
spec:
  secretStoreRef:
    name: cop-{{ (.Values.global).secrets.externalStore.paths.mavenTaskAuthSecrets.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 1440m0s

  target:
    name: '{{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-maven-task-auth-secrets'
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: {{ (.Values.global).secrets.externalStore.paths.mavenTaskAuthSecrets.id }}
  {{- end }}

  {{- if and (.Values.global).secrets.externalStore.paths (.Values.global).secrets.externalStore.paths.mavenTaskFileSecrets }}
---
# ExternalSecret: maven task file Secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    {{- include "java-pipeline.annotations" . | nindent 4 }}
  name: {{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-ex-maven-task-file-secrets
spec:
  secretStoreRef:
    name: cop-{{ (.Values.global).secrets.externalStore.paths.mavenTaskFileSecrets.vault }}
    kind: SecretStore

  # Refresh: daily
  refreshInterval: 1440m0s

  target:
    name: '{{ include "java-pipeline.resourceBaseName" . }}-{{ include "java-pipeline.pipelinePrefix" . }}-maven-task-file-secrets'
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: {{ (.Values.global).secrets.externalStore.paths.mavenTaskFileSecrets.id }}
        decodingStrategy: Base64
  {{- end }}
{{- end }}

